// Mocks generated by Mockito 5.4.6 from annotations
// in dart_ipfs/test/protocols/graphsync/graphsync_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i12;

import 'package:dart_ipfs/src/core/cid.dart' as _i16;
import 'package:dart_ipfs/src/core/data_structures/block.dart' as _i4;
import 'package:dart_ipfs/src/core/data_structures/blockstore.dart' as _i18;
import 'package:dart_ipfs/src/core/data_structures/metadata.dart' as _i5;
import 'package:dart_ipfs/src/core/data_structures/pin_manager.dart' as _i6;
import 'package:dart_ipfs/src/core/ipfs_node/ipld_handler.dart' as _i15;
import 'package:dart_ipfs/src/core/ipld/selectors/ipld_selector.dart' as _i17;
import 'package:dart_ipfs/src/proto/generated/core/blockstore.pb.dart' as _i7;
import 'package:dart_ipfs/src/protocols/bitswap/bitswap_handler.dart' as _i14;
import 'package:dart_ipfs/src/protocols/bitswap/message.dart' as _i13;
import 'package:dart_ipfs/src/protocols/dht/routing_table.dart' as _i3;
import 'package:dart_ipfs/src/transport/p2plib_router.dart' as _i8;
import 'package:dart_ipfs/src/transport/router_events.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:p2plib/p2plib.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePeerId_0 extends _i1.SmartFake implements _i2.PeerId {
  _FakePeerId_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouterL2_1 extends _i1.SmartFake implements _i2.RouterL2 {
  _FakeRouterL2_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutingTable_2 extends _i1.SmartFake implements _i3.RoutingTable {
  _FakeRoutingTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFullAddress_3 extends _i1.SmartFake implements _i2.FullAddress {
  _FakeFullAddress_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBlock_4 extends _i1.SmartFake implements _i4.Block {
  _FakeBlock_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPLDMetadata_5 extends _i1.SmartFake implements _i5.IPLDMetadata {
  _FakeIPLDMetadata_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePinManager_6 extends _i1.SmartFake implements _i6.PinManager {
  _FakePinManager_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetBlockResponse_7 extends _i1.SmartFake
    implements _i7.GetBlockResponse {
  _FakeGetBlockResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddBlockResponse_8 extends _i1.SmartFake
    implements _i7.AddBlockResponse {
  _FakeAddBlockResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveBlockResponse_9 extends _i1.SmartFake
    implements _i7.RemoveBlockResponse {
  _FakeRemoveBlockResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [P2plibRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockP2plibRouter extends _i1.Mock implements _i8.P2plibRouter {
  MockP2plibRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  List<String> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get listeningAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#listeningAddresses),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i2.PeerId get peerId =>
      (super.noSuchMethod(
            Invocation.getter(#peerId),
            returnValue: _FakePeerId_0(this, Invocation.getter(#peerId)),
          )
          as _i2.PeerId);

  @override
  Map<_i2.PeerId, _i2.Route> get routes =>
      (super.noSuchMethod(
            Invocation.getter(#routes),
            returnValue: <_i2.PeerId, _i2.Route>{},
          )
          as Map<_i2.PeerId, _i2.Route>);

  @override
  _i2.RouterL2 get routerL0 =>
      (super.noSuchMethod(
            Invocation.getter(#routerL0),
            returnValue: _FakeRouterL2_1(this, Invocation.getter(#routerL0)),
          )
          as _i2.RouterL2);

  @override
  _i10.Stream<_i11.ConnectionEvent> get connectionEvents =>
      (super.noSuchMethod(
            Invocation.getter(#connectionEvents),
            returnValue: _i10.Stream<_i11.ConnectionEvent>.empty(),
          )
          as _i10.Stream<_i11.ConnectionEvent>);

  @override
  _i10.Stream<_i11.MessageEvent> get messageEvents =>
      (super.noSuchMethod(
            Invocation.getter(#messageEvents),
            returnValue: _i10.Stream<_i11.MessageEvent>.empty(),
          )
          as _i10.Stream<_i11.MessageEvent>);

  @override
  _i10.Stream<_i11.DHTEvent> get dhtEvents =>
      (super.noSuchMethod(
            Invocation.getter(#dhtEvents),
            returnValue: _i10.Stream<_i11.DHTEvent>.empty(),
          )
          as _i10.Stream<_i11.DHTEvent>);

  @override
  _i10.Stream<_i11.PubSubEvent> get pubSubEvents =>
      (super.noSuchMethod(
            Invocation.getter(#pubSubEvents),
            returnValue: _i10.Stream<_i11.PubSubEvent>.empty(),
          )
          as _i10.Stream<_i11.PubSubEvent>);

  @override
  _i10.Stream<_i11.StreamEvent> get streamEvents =>
      (super.noSuchMethod(
            Invocation.getter(#streamEvents),
            returnValue: _i10.Stream<_i11.StreamEvent>.empty(),
          )
          as _i10.Stream<_i11.StreamEvent>);

  @override
  _i10.Stream<_i11.ErrorEvent> get errorEvents =>
      (super.noSuchMethod(
            Invocation.getter(#errorEvents),
            returnValue: _i10.Stream<_i11.ErrorEvent>.empty(),
          )
          as _i10.Stream<_i11.ErrorEvent>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i2.PeerId get localPeerId =>
      (super.noSuchMethod(
            Invocation.getter(#localPeerId),
            returnValue: _FakePeerId_0(this, Invocation.getter(#localPeerId)),
          )
          as _i2.PeerId);

  @override
  List<String> resolvePeer(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeer, [peerIdStr]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> connect(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [multiaddress]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> disconnect(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [multiaddress]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  List<String> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i10.Future<void> sendMessage(
    String? peerIdStr,
    _i12.Uint8List? message, {
    String? protocolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [peerIdStr, message],
              {#protocolId: protocolId},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Stream<String> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i10.Stream<String>.empty(),
          )
          as _i10.Stream<String>);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void onMessage(void Function(_i13.Message)? handler) => super.noSuchMethod(
    Invocation.method(#onMessage, [handler]),
    returnValueForMissingStub: null,
  );

  @override
  void registerProtocolHandler(
    String? protocolId,
    void Function(_i11.NetworkPacket)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#registerProtocolHandler, [protocolId, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void removeMessageHandler(String? protocolId) => super.noSuchMethod(
    Invocation.method(#removeMessageHandler, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> sendDatagram({
    required List<String>? addresses,
    required _i12.Uint8List? datagram,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendDatagram, [], {
              #addresses: addresses,
              #datagram: datagram,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i3.RoutingTable getRoutingTable() =>
      (super.noSuchMethod(
            Invocation.method(#getRoutingTable, []),
            returnValue: _FakeRoutingTable_2(
              this,
              Invocation.method(#getRoutingTable, []),
            ),
          )
          as _i3.RoutingTable);

  @override
  _i10.Future<void> emitEvent(String? topic, _i12.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#emitEvent, [topic, data]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void onEvent(String? topic, void Function(_i11.NetworkMessage)? handler) =>
      super.noSuchMethod(
        Invocation.method(#onEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void offEvent(String? topic, void Function(_i11.NetworkMessage)? handler) =>
      super.noSuchMethod(
        Invocation.method(#offEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i2.FullAddress parseMultiaddr(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#parseMultiaddr, [multiaddr]),
            returnValue: _FakeFullAddress_3(
              this,
              Invocation.method(#parseMultiaddr, [multiaddr]),
            ),
          )
          as _i2.FullAddress);

  @override
  bool isConnectedPeer(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#isConnectedPeer, [peerIdStr]),
            returnValue: false,
          )
          as bool);

  @override
  void registerProtocol(String? protocolId) => super.noSuchMethod(
    Invocation.method(#registerProtocol, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i12.Uint8List> sendRequest(
    String? peerId,
    String? protocolId,
    _i12.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i10.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
          )
          as _i10.Future<_i12.Uint8List>);

  @override
  _i10.Future<void> broadcastMessage(
    String? protocolId,
    _i12.Uint8List? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastMessage, [protocolId, message]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [BitswapHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockBitswapHandler extends _i1.Mock implements _i14.BitswapHandler {
  MockBitswapHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get bandwidthSent =>
      (super.noSuchMethod(Invocation.getter(#bandwidthSent), returnValue: 0)
          as int);

  @override
  int get bandwidthReceived =>
      (super.noSuchMethod(Invocation.getter(#bandwidthReceived), returnValue: 0)
          as int);

  @override
  _i10.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> handleBlocks(List<_i4.Block>? blocks) =>
      (super.noSuchMethod(
            Invocation.method(#handleBlocks, [blocks]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i4.Block>> want(
    List<String>? cids, {
    int? priority = 1,
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #want,
              [cids],
              {#priority: priority, #timeout: timeout},
            ),
            returnValue: _i10.Future<List<_i4.Block>>.value(<_i4.Block>[]),
          )
          as _i10.Future<List<_i4.Block>>);

  @override
  _i10.Future<void> handleWantRequest(String? cidStr) =>
      (super.noSuchMethod(
            Invocation.method(#handleWantRequest, [cidStr]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i4.Block?> wantBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#wantBlock, [cid]),
            returnValue: _i10.Future<_i4.Block?>.value(),
          )
          as _i10.Future<_i4.Block?>);

  @override
  _i10.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);
}

/// A class which mocks [IPLDHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPLDHandler extends _i1.Mock implements _i15.IPLDHandler {
  MockIPLDHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i4.Block> put(
    dynamic value, {
    String? codec = 'dag-cbor',
    String? schemaType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [value],
              {#codec: codec, #schemaType: schemaType},
            ),
            returnValue: _i10.Future<_i4.Block>.value(
              _FakeBlock_4(
                this,
                Invocation.method(
                  #put,
                  [value],
                  {#codec: codec, #schemaType: schemaType},
                ),
              ),
            ),
          )
          as _i10.Future<_i4.Block>);

  @override
  _i10.Future<dynamic> get(_i16.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#get, [cid]),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<(dynamic, String?)> resolveLink(_i16.CID? root, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#resolveLink, [root, path]),
            returnValue: _i10.Future<(dynamic, String?)>.value((null, null)),
          )
          as _i10.Future<(dynamic, String?)>);

  @override
  _i10.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<dynamic>> executeSelector(
    _i16.CID? rootCid,
    _i17.IPLDSelector? selector,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#executeSelector, [rootCid, selector]),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  void registerSchema(String? name, Map<String, dynamic>? schema) =>
      super.noSuchMethod(
        Invocation.method(#registerSchema, [name, schema]),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<dynamic> resolvePath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePath, [path]),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i5.IPLDMetadata> getMetadata(_i16.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, [cid]),
            returnValue: _i10.Future<_i5.IPLDMetadata>.value(
              _FakeIPLDMetadata_5(this, Invocation.method(#getMetadata, [cid])),
            ),
          )
          as _i10.Future<_i5.IPLDMetadata>);

  @override
  _i10.Future<(dynamic, _i5.IPLDMetadata)> resolveWithMetadata(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#resolveWithMetadata, [path]),
            returnValue: _i10.Future<(dynamic, _i5.IPLDMetadata)>.value((
              null,
              _FakeIPLDMetadata_5(
                this,
                Invocation.method(#resolveWithMetadata, [path]),
              ),
            )),
          )
          as _i10.Future<(dynamic, _i5.IPLDMetadata)>);
}

/// A class which mocks [BlockStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockStore extends _i1.Mock implements _i18.BlockStore {
  MockBlockStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#path)),
          )
          as String);

  @override
  _i6.PinManager get pinManager =>
      (super.noSuchMethod(
            Invocation.getter(#pinManager),
            returnValue: _FakePinManager_6(
              this,
              Invocation.getter(#pinManager),
            ),
          )
          as _i6.PinManager);

  @override
  _i10.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i7.GetBlockResponse> getBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#getBlock, [cid]),
            returnValue: _i10.Future<_i7.GetBlockResponse>.value(
              _FakeGetBlockResponse_7(
                this,
                Invocation.method(#getBlock, [cid]),
              ),
            ),
          )
          as _i10.Future<_i7.GetBlockResponse>);

  @override
  _i10.Future<_i7.AddBlockResponse> putBlock(_i4.Block? block) =>
      (super.noSuchMethod(
            Invocation.method(#putBlock, [block]),
            returnValue: _i10.Future<_i7.AddBlockResponse>.value(
              _FakeAddBlockResponse_8(
                this,
                Invocation.method(#putBlock, [block]),
              ),
            ),
          )
          as _i10.Future<_i7.AddBlockResponse>);

  @override
  _i10.Future<_i7.RemoveBlockResponse> removeBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#removeBlock, [cid]),
            returnValue: _i10.Future<_i7.RemoveBlockResponse>.value(
              _FakeRemoveBlockResponse_9(
                this,
                Invocation.method(#removeBlock, [cid]),
              ),
            ),
          )
          as _i10.Future<_i7.RemoveBlockResponse>);

  @override
  _i10.Future<bool> hasBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#hasBlock, [cid]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<_i4.Block>> getAllBlocks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBlocks, []),
            returnValue: _i10.Future<List<_i4.Block>>.value(<_i4.Block>[]),
          )
          as _i10.Future<List<_i4.Block>>);

  @override
  _i10.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);
}
