include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/src/proto/generated/**
    - "**/*.g.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbserver.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore
    unused_import: error
    unused_local_variable: error
    dead_code: error
    public_member_api_docs: info
    package_api_docs: info

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_single_quotes
    - unawaited_futures
    - directives_ordering
    - prefer_final_fields
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - sort_constructors_first
    - package_api_docs
    - public_member_api_docs
