// ignore_for_file: avoid_print
import 'dart:io';

void main() {
  final file = File('coverage/lcov.info');
  if (!file.existsSync()) {
    print('lcov.info not found');
    return;
  }

  final lines = file.readAsLinesSync();
  String? currentFile;
  int foundLines = 0;
  int hitLines = 0;
  final results = <Map<String, dynamic>>[];

  for (final line in lines) {
    if (line.startsWith('SF:')) {
      currentFile = line.substring(3);
    } else if (line.startsWith('LF:')) {
      foundLines = int.parse(line.substring(3));
    } else if (line.startsWith('LH:')) {
      hitLines = int.parse(line.substring(3));
      if (foundLines > 0) {
        final percentage = (hitLines / foundLines * 100);
        results.add({
          'file': currentFile,
          'percentage': percentage,
          'hit': hitLines,
          'total': foundLines,
        });
      }
    }
  }

  results.sort(
    (a, b) => (a['percentage'] as num).compareTo(b['percentage'] as num),
  );

  print('### Global Coverage Report (Sorted by lowest first) ###');
  for (var res in results) {
    // Skip autogenerated files
    final fileName = res['file'] as String;
    if (fileName.contains('.pb.') ||
        fileName.contains('.g.dart') ||
        fileName.contains('.mocks.dart')) {
      continue;
    }
    print(
      '${res['percentage'].toStringAsFixed(2)}% (${res['hit']}/${res['total']}) - ${res['file']}',
    );
  }
}
