// Mocks generated by Mockito from annotations
// in dart_ipfs/test/core/services/health_check_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i13;
import 'dart:typed_data' as _i16;

import 'package:dart_ipfs/src/core/data_structures/block.dart' as _i18;
import 'package:dart_ipfs/src/core/data_structures/blockstore.dart' as _i6;
import 'package:dart_ipfs/src/core/data_structures/link.dart' as _i17;
import 'package:dart_ipfs/src/core/data_structures/peer.dart' as _i15;
import 'package:dart_ipfs/src/core/data_structures/pin_manager.dart' as _i9;
import 'package:dart_ipfs/src/core/ipfs_node/ipfs_node.dart' as _i11;
import 'package:dart_ipfs/src/core/ipfs_node/network_manager.dart' as _i5;
import 'package:dart_ipfs/src/core/mfs/mfs_manager.dart' as _i2;
import 'package:dart_ipfs/src/core/plugins/ipfs_plugin.dart' as _i3;
import 'package:dart_ipfs/src/core/security/security_manager.dart' as _i4;
import 'package:dart_ipfs/src/core/storage/datastore.dart' as _i8;
import 'package:dart_ipfs/src/proto/generated/core/blockstore.pb.dart' as _i10;
import 'package:dart_ipfs/src/protocols/dht/dht_client.dart' as _i7;
import 'package:dart_ipfs/src/protocols/pubsub/pubsub_message.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMFSManager_0 extends _i1.SmartFake implements _i2.MFSManager {
  _FakeMFSManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePluginManager_1 extends _i1.SmartFake implements _i3.PluginManager {
  _FakePluginManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecurityManager_2 extends _i1.SmartFake
    implements _i4.SecurityManager {
  _FakeSecurityManager_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetworkManager_3 extends _i1.SmartFake
    implements _i5.NetworkManager {
  _FakeNetworkManager_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBlockStore_4 extends _i1.SmartFake implements _i6.BlockStore {
  _FakeBlockStore_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDHTClient_5 extends _i1.SmartFake implements _i7.DHTClient {
  _FakeDHTClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatastore_6 extends _i1.SmartFake implements _i8.Datastore {
  _FakeDatastore_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePinManager_7 extends _i1.SmartFake implements _i9.PinManager {
  _FakePinManager_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetBlockResponse_8 extends _i1.SmartFake
    implements _i10.GetBlockResponse {
  _FakeGetBlockResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddBlockResponse_9 extends _i1.SmartFake
    implements _i10.AddBlockResponse {
  _FakeAddBlockResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveBlockResponse_10 extends _i1.SmartFake
    implements _i10.RemoveBlockResponse {
  _FakeRemoveBlockResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IPFSNode].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPFSNode extends _i1.Mock implements _i11.IPFSNode {
  MockIPFSNode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.NodeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i11.NodeState.stopped,
          )
          as _i11.NodeState);

  @override
  _i2.MFSManager get mfs =>
      (super.noSuchMethod(
            Invocation.getter(#mfs),
            returnValue: _FakeMFSManager_0(this, Invocation.getter(#mfs)),
          )
          as _i2.MFSManager);

  @override
  _i3.PluginManager get plugins =>
      (super.noSuchMethod(
            Invocation.getter(#plugins),
            returnValue: _FakePluginManager_1(
              this,
              Invocation.getter(#plugins),
            ),
          )
          as _i3.PluginManager);

  @override
  _i4.SecurityManager get securityManager =>
      (super.noSuchMethod(
            Invocation.getter(#securityManager),
            returnValue: _FakeSecurityManager_2(
              this,
              Invocation.getter(#securityManager),
            ),
          )
          as _i4.SecurityManager);

  @override
  _i5.NetworkManager get networkManager =>
      (super.noSuchMethod(
            Invocation.getter(#networkManager),
            returnValue: _FakeNetworkManager_3(
              this,
              Invocation.getter(#networkManager),
            ),
          )
          as _i5.NetworkManager);

  @override
  bool get isRunning =>
      (super.noSuchMethod(Invocation.getter(#isRunning), returnValue: false)
          as bool);

  @override
  String get peerId =>
      (super.noSuchMethod(
            Invocation.getter(#peerId),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#peerId),
            ),
          )
          as String);

  @override
  _i13.Stream<Map<String, dynamic>> get bandwidthMetrics =>
      (super.noSuchMethod(
            Invocation.getter(#bandwidthMetrics),
            returnValue: _i13.Stream<Map<String, dynamic>>.empty(),
          )
          as _i13.Stream<Map<String, dynamic>>);

  @override
  int get bandwidthOut =>
      (super.noSuchMethod(Invocation.getter(#bandwidthOut), returnValue: 0)
          as int);

  @override
  int get bandwidthIn =>
      (super.noSuchMethod(Invocation.getter(#bandwidthIn), returnValue: 0)
          as int);

  @override
  int get dhtPeerCount =>
      (super.noSuchMethod(Invocation.getter(#dhtPeerCount), returnValue: 0)
          as int);

  @override
  List<String> get addresses =>
      (super.noSuchMethod(
            Invocation.getter(#addresses),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i6.BlockStore get blockStore =>
      (super.noSuchMethod(
            Invocation.getter(#blockStore),
            returnValue: _FakeBlockStore_4(
              this,
              Invocation.getter(#blockStore),
            ),
          )
          as _i6.BlockStore);

  @override
  _i7.DHTClient get dhtClient =>
      (super.noSuchMethod(
            Invocation.getter(#dhtClient),
            returnValue: _FakeDHTClient_5(this, Invocation.getter(#dhtClient)),
          )
          as _i7.DHTClient);

  @override
  _i13.Future<List<String>> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<String> get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i13.Future<String>.value(
              _i12.dummyValue<String>(this, Invocation.getter(#publicKey)),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<List<String>> get pinnedCids =>
      (super.noSuchMethod(
            Invocation.getter(#pinnedCids),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Stream<_i14.PubSubMessage> get pubsubMessages =>
      (super.noSuchMethod(
            Invocation.getter(#pubsubMessages),
            returnValue: _i13.Stream<_i14.PubSubMessage>.empty(),
          )
          as _i13.Stream<_i14.PubSubMessage>);

  @override
  _i8.Datastore get datastore =>
      (super.noSuchMethod(
            Invocation.getter(#datastore),
            returnValue: _FakeDatastore_6(this, Invocation.getter(#datastore)),
          )
          as _i8.Datastore);

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  _i13.Stream<_i15.Peer> get discoveredPeers =>
      (super.noSuchMethod(
            Invocation.getter(#discoveredPeers),
            returnValue: _i13.Stream<_i15.Peer>.empty(),
          )
          as _i13.Stream<_i15.Peer>);

  @override
  _i13.Stream<String> get onNewContent =>
      (super.noSuchMethod(
            Invocation.getter(#onNewContent),
            returnValue: _i13.Stream<String>.empty(),
          )
          as _i13.Stream<String>);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i13.Future<_i16.Uint8List?> cat(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#cat, [cid]),
            returnValue: _i13.Future<_i16.Uint8List?>.value(),
          )
          as _i13.Future<_i16.Uint8List?>);

  @override
  _i13.Future<void> connectToPeer(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#connectToPeer, [multiaddr]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> disconnectFromPeer(String? peerIdOrAddr) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromPeer, [peerIdOrAddr]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<String> resolveIPNS(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#resolveIPNS, [name]),
            returnValue: _i13.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [name]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<void> subscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [topic]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> unsubscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [topic]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> publish(String? topic, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [topic, message]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  List<String> pubsubLs() =>
      (super.noSuchMethod(
            Invocation.method(#pubsubLs, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i13.Future<List<String>> pubsubPeers(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#pubsubPeers, [topic]),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> restart() =>
      (super.noSuchMethod(
            Invocation.method(#restart, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<String> addFile(_i16.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#addFile, [data]),
            returnValue: _i13.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#addFile, [data]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<String> addFileStream(_i13.Stream<List<int>>? dataStream) =>
      (super.noSuchMethod(
            Invocation.method(#addFileStream, [dataStream]),
            returnValue: _i13.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#addFileStream, [dataStream]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<String> addDirectory(Map<String, dynamic>? directoryContent) =>
      (super.noSuchMethod(
            Invocation.method(#addDirectory, [directoryContent]),
            returnValue: _i13.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#addDirectory, [directoryContent]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  void setGatewayMode(_i11.GatewayMode? mode, {String? customUrl}) =>
      super.noSuchMethod(
        Invocation.method(#setGatewayMode, [mode], {#customUrl: customUrl}),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<_i16.Uint8List?> get(String? cid, {String? path = ''}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [cid], {#path: path}),
            returnValue: _i13.Future<_i16.Uint8List?>.value(),
          )
          as _i13.Future<_i16.Uint8List?>);

  @override
  _i13.Future<List<_i17.Link>> ls(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#ls, [cid]),
            returnValue: _i13.Future<List<_i17.Link>>.value(<_i17.Link>[]),
          )
          as _i13.Future<List<_i17.Link>>);

  @override
  _i13.Future<void> pin(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#pin, [cid]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> unpin(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#unpin, [cid]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<String> publishIPNS(String? cid, {required String? keyName}) =>
      (super.noSuchMethod(
            Invocation.method(#publishIPNS, [cid], {#keyName: keyName}),
            returnValue: _i13.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#publishIPNS, [cid], {#keyName: keyName}),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<String> keyGen(
    String? name, {
    String? type = 'ed25519',
    int? size,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#keyGen, [name], {#type: type, #size: size}),
            returnValue: _i13.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#keyGen, [name], {#type: type, #size: size}),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<List<String>> keyList() =>
      (super.noSuchMethod(
            Invocation.method(#keyList, []),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<String> keyImport(String? name, _i16.Uint8List? privateKey) =>
      (super.noSuchMethod(
            Invocation.method(#keyImport, [name, privateKey]),
            returnValue: _i13.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#keyImport, [name, privateKey]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<_i16.Uint8List> keyExport(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#keyExport, [name]),
            returnValue: _i13.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
          )
          as _i13.Future<_i16.Uint8List>);

  @override
  _i13.Future<void> keyRm(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#keyRm, [name]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> importCAR(_i16.Uint8List? carFile) =>
      (super.noSuchMethod(
            Invocation.method(#importCAR, [carFile]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i16.Uint8List> exportCAR(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#exportCAR, [cid]),
            returnValue: _i13.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
          )
          as _i13.Future<_i16.Uint8List>);

  @override
  _i13.Future<List<String>> findProviders(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<void> requestBlock(String? cid, _i15.Peer? peer) =>
      (super.noSuchMethod(
            Invocation.method(#requestBlock, [cid, peer]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<String> resolveDNSLink(String? domainName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDNSLink, [domainName]),
            returnValue: _i13.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#resolveDNSLink, [domainName]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<Map<String, dynamic>> getHealthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getHealthStatus, []),
            returnValue: _i13.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i13.Future<Map<String, dynamic>>);
}

/// A class which mocks [BlockStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockStore extends _i1.Mock implements _i6.BlockStore {
  MockBlockStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  _i9.PinManager get pinManager =>
      (super.noSuchMethod(
            Invocation.getter(#pinManager),
            returnValue: _FakePinManager_7(
              this,
              Invocation.getter(#pinManager),
            ),
          )
          as _i9.PinManager);

  @override
  _i13.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> flush() =>
      (super.noSuchMethod(
            Invocation.method(#flush, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i10.GetBlockResponse> getBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#getBlock, [cid]),
            returnValue: _i13.Future<_i10.GetBlockResponse>.value(
              _FakeGetBlockResponse_8(
                this,
                Invocation.method(#getBlock, [cid]),
              ),
            ),
          )
          as _i13.Future<_i10.GetBlockResponse>);

  @override
  _i13.Future<_i10.AddBlockResponse> putBlock(_i18.Block? block) =>
      (super.noSuchMethod(
            Invocation.method(#putBlock, [block]),
            returnValue: _i13.Future<_i10.AddBlockResponse>.value(
              _FakeAddBlockResponse_9(
                this,
                Invocation.method(#putBlock, [block]),
              ),
            ),
          )
          as _i13.Future<_i10.AddBlockResponse>);

  @override
  _i13.Future<_i10.RemoveBlockResponse> removeBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#removeBlock, [cid]),
            returnValue: _i13.Future<_i10.RemoveBlockResponse>.value(
              _FakeRemoveBlockResponse_10(
                this,
                Invocation.method(#removeBlock, [cid]),
              ),
            ),
          )
          as _i13.Future<_i10.RemoveBlockResponse>);

  @override
  _i13.Future<bool> hasBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#hasBlock, [cid]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<List<_i18.Block>> getAllBlocks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBlocks, []),
            returnValue: _i13.Future<List<_i18.Block>>.value(<_i18.Block>[]),
          )
          as _i13.Future<List<_i18.Block>>);

  @override
  _i13.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i13.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i13.Future<Map<String, dynamic>>);

  @override
  _i13.Future<int> gc() =>
      (super.noSuchMethod(
            Invocation.method(#gc, []),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);
}
