// Mocks generated by Mockito 5.4.6 from annotations
// in dart_ipfs/test/routing/content_routing_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i13;

import 'package:dart_ipfs/src/core/cid.dart' as _i15;
import 'package:dart_ipfs/src/core/config/ipfs_config.dart' as _i6;
import 'package:dart_ipfs/src/core/ipfs_node/ipfs_node.dart' as _i2;
import 'package:dart_ipfs/src/core/ipfs_node/network_handler.dart' as _i7;
import 'package:dart_ipfs/src/core/types/peer_id.dart' as _i8;
import 'package:dart_ipfs/src/network/router.dart' as _i4;
import 'package:dart_ipfs/src/proto/generated/dht/ipfs_node_network_events.pb.dart'
    as _i11;
import 'package:dart_ipfs/src/protocols/dht/dht_client.dart' as _i14;
import 'package:dart_ipfs/src/protocols/dht/kademlia_routing_table.dart' as _i9;
import 'package:dart_ipfs/src/transport/circuit_relay_client.dart' as _i5;
import 'package:dart_ipfs/src/transport/router_interface.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIPFSNode_0 extends _i1.SmartFake implements _i2.IPFSNode {
  _FakeIPFSNode_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouterInterface_1 extends _i1.SmartFake
    implements _i3.RouterInterface {
  _FakeRouterInterface_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouter_2 extends _i1.SmartFake implements _i4.Router {
  _FakeRouter_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCircuitRelayClient_3 extends _i1.SmartFake
    implements _i5.CircuitRelayClient {
  _FakeCircuitRelayClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPFSConfig_4 extends _i1.SmartFake implements _i6.IPFSConfig {
  _FakeIPFSConfig_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetworkHandler_5 extends _i1.SmartFake
    implements _i7.NetworkHandler {
  _FakeNetworkHandler_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeerId_6 extends _i1.SmartFake implements _i8.PeerId {
  _FakePeerId_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKademliaRoutingTable_7 extends _i1.SmartFake
    implements _i9.KademliaRoutingTable {
  _FakeKademliaRoutingTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkHandler extends _i1.Mock implements _i7.NetworkHandler {
  @override
  _i2.IPFSNode get ipfsNode =>
      (super.noSuchMethod(
            Invocation.getter(#ipfsNode),
            returnValue: _FakeIPFSNode_0(this, Invocation.getter(#ipfsNode)),
            returnValueForMissingStub: _FakeIPFSNode_0(
              this,
              Invocation.getter(#ipfsNode),
            ),
          )
          as _i2.IPFSNode);

  @override
  _i3.RouterInterface get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
            returnValueForMissingStub: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i3.RouterInterface);

  @override
  _i10.Stream<_i11.NetworkEvent> get networkEvents =>
      (super.noSuchMethod(
            Invocation.getter(#networkEvents),
            returnValue: _i10.Stream<_i11.NetworkEvent>.empty(),
            returnValueForMissingStub: _i10.Stream<_i11.NetworkEvent>.empty(),
          )
          as _i10.Stream<_i11.NetworkEvent>);

  @override
  _i4.Router get dhtRouter =>
      (super.noSuchMethod(
            Invocation.getter(#dhtRouter),
            returnValue: _FakeRouter_2(this, Invocation.getter(#dhtRouter)),
            returnValueForMissingStub: _FakeRouter_2(
              this,
              Invocation.getter(#dhtRouter),
            ),
          )
          as _i4.Router);

  @override
  _i5.CircuitRelayClient get circuitRelayClient =>
      (super.noSuchMethod(
            Invocation.getter(#circuitRelayClient),
            returnValue: _FakeCircuitRelayClient_3(
              this,
              Invocation.getter(#circuitRelayClient),
            ),
            returnValueForMissingStub: _FakeCircuitRelayClient_3(
              this,
              Invocation.getter(#circuitRelayClient),
            ),
          )
          as _i5.CircuitRelayClient);

  @override
  _i6.IPFSConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeIPFSConfig_4(this, Invocation.getter(#config)),
            returnValueForMissingStub: _FakeIPFSConfig_4(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i6.IPFSConfig);

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  set ipfsNode(_i2.IPFSNode? value) => super.noSuchMethod(
    Invocation.setter(#ipfsNode, value),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> connectToPeer(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connectToPeer, [multiaddress]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> disconnectFromPeer(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromPeer, [multiaddress]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<String>> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<void> sendMessage(String? peerId, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [peerId, message]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Stream<String> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i10.Stream<String>.empty(),
            returnValueForMissingStub: _i10.Stream<String>.empty(),
          )
          as _i10.Stream<String>);

  @override
  void setIpfsNode(_i2.IPFSNode? node) => super.noSuchMethod(
    Invocation.method(#setIpfsNode, [node]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i13.Uint8List?> sendRequest(
    String? peerId,
    String? protocolId,
    _i13.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i10.Future<_i13.Uint8List?>.value(),
            returnValueForMissingStub: _i10.Future<_i13.Uint8List?>.value(),
          )
          as _i10.Future<_i13.Uint8List?>);

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> canConnectDirectly(String? peerAddress) =>
      (super.noSuchMethod(
            Invocation.method(#canConnectDirectly, [peerAddress]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> testDialback() =>
      (super.noSuchMethod(
            Invocation.method(#testDialback, []),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);
}

/// A class which mocks [DHTClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDHTClient extends _i1.Mock implements _i14.DHTClient {
  @override
  _i2.IPFSNode get node =>
      (super.noSuchMethod(
            Invocation.getter(#node),
            returnValue: _FakeIPFSNode_0(this, Invocation.getter(#node)),
            returnValueForMissingStub: _FakeIPFSNode_0(
              this,
              Invocation.getter(#node),
            ),
          )
          as _i2.IPFSNode);

  @override
  _i7.NetworkHandler get networkHandler =>
      (super.noSuchMethod(
            Invocation.getter(#networkHandler),
            returnValue: _FakeNetworkHandler_5(
              this,
              Invocation.getter(#networkHandler),
            ),
            returnValueForMissingStub: _FakeNetworkHandler_5(
              this,
              Invocation.getter(#networkHandler),
            ),
          )
          as _i7.NetworkHandler);

  @override
  _i8.PeerId get peerId =>
      (super.noSuchMethod(
            Invocation.getter(#peerId),
            returnValue: _FakePeerId_6(this, Invocation.getter(#peerId)),
            returnValueForMissingStub: _FakePeerId_6(
              this,
              Invocation.getter(#peerId),
            ),
          )
          as _i8.PeerId);

  @override
  _i8.PeerId get associatedPeerId =>
      (super.noSuchMethod(
            Invocation.getter(#associatedPeerId),
            returnValue: _FakePeerId_6(
              this,
              Invocation.getter(#associatedPeerId),
            ),
            returnValueForMissingStub: _FakePeerId_6(
              this,
              Invocation.getter(#associatedPeerId),
            ),
          )
          as _i8.PeerId);

  @override
  _i9.KademliaRoutingTable get kademliaRoutingTable =>
      (super.noSuchMethod(
            Invocation.getter(#kademliaRoutingTable),
            returnValue: _FakeKademliaRoutingTable_7(
              this,
              Invocation.getter(#kademliaRoutingTable),
            ),
            returnValueForMissingStub: _FakeKademliaRoutingTable_7(
              this,
              Invocation.getter(#kademliaRoutingTable),
            ),
          )
          as _i9.KademliaRoutingTable);

  @override
  _i3.RouterInterface get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
            returnValueForMissingStub: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i3.RouterInterface);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set peerId(_i8.PeerId? value) => super.noSuchMethod(
    Invocation.setter(#peerId, value),
    returnValueForMissingStub: null,
  );

  @override
  set associatedPeerId(_i8.PeerId? value) => super.noSuchMethod(
    Invocation.setter(#associatedPeerId, value),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i8.PeerId getRoutingKey(String? cidStr) =>
      (super.noSuchMethod(
            Invocation.method(#getRoutingKey, [cidStr]),
            returnValue: _FakePeerId_6(
              this,
              Invocation.method(#getRoutingKey, [cidStr]),
            ),
            returnValueForMissingStub: _FakePeerId_6(
              this,
              Invocation.method(#getRoutingKey, [cidStr]),
            ),
          )
          as _i8.PeerId);

  @override
  _i10.Future<List<_i8.PeerId>> findProviders(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i10.Future<List<_i8.PeerId>>.value(<_i8.PeerId>[]),
            returnValueForMissingStub: _i10.Future<List<_i8.PeerId>>.value(
              <_i8.PeerId>[],
            ),
          )
          as _i10.Future<List<_i8.PeerId>>);

  @override
  _i10.Future<_i8.PeerId?> findPeer(_i8.PeerId? id) =>
      (super.noSuchMethod(
            Invocation.method(#findPeer, [id]),
            returnValue: _i10.Future<_i8.PeerId?>.value(),
            returnValueForMissingStub: _i10.Future<_i8.PeerId?>.value(),
          )
          as _i10.Future<_i8.PeerId?>);

  @override
  _i10.Future<void> addProvider(String? cid, String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#addProvider, [cid, providerId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> addProviders(List<_i15.CID>? cids, String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#addProviders, [cids, providerId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> storeValue(_i13.Uint8List? key, _i13.Uint8List? value) =>
      (super.noSuchMethod(
            Invocation.method(#storeValue, [key, value]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> storeValueToPeer(
    _i8.PeerId? peer,
    _i13.Uint8List? key,
    _i13.Uint8List? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeValueToPeer, [peer, key, value]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i13.Uint8List?> getValue(_i13.Uint8List? key) =>
      (super.noSuchMethod(
            Invocation.method(#getValue, [key]),
            returnValue: _i10.Future<_i13.Uint8List?>.value(),
            returnValueForMissingStub: _i10.Future<_i13.Uint8List?>.value(),
          )
          as _i10.Future<_i13.Uint8List?>);

  @override
  _i10.Future<bool> storeValueRaw(_i13.Uint8List? key, _i13.Uint8List? value) =>
      (super.noSuchMethod(
            Invocation.method(#storeValueRaw, [key, value]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i13.Uint8List?> getValueRaw(_i13.Uint8List? key) =>
      (super.noSuchMethod(
            Invocation.method(#getValueRaw, [key]),
            returnValue: _i10.Future<_i13.Uint8List?>.value(),
            returnValueForMissingStub: _i10.Future<_i13.Uint8List?>.value(),
          )
          as _i10.Future<_i13.Uint8List?>);

  @override
  _i10.Future<bool> checkValueOnPeer(_i8.PeerId? peer, _i13.Uint8List? key) =>
      (super.noSuchMethod(
            Invocation.method(#checkValueOnPeer, [peer, key]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> sendMessageRaw(
    _i8.PeerId? peer,
    _i13.Uint8List? msgBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessageRaw, [peer, msgBytes]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  bool listsEqual(List<int>? a, List<int>? b) =>
      (super.noSuchMethod(
            Invocation.method(#listsEqual, [a, b]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<List<String>> getAllStoredKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getAllStoredKeys, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<void> reprovide() =>
      (super.noSuchMethod(
            Invocation.method(#reprovide, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateKeyRepublishTime(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#updateKeyRepublishTime, [key]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}
