// Mocks generated by Mockito 5.4.6 from annotations
// in dart_ipfs/test/protocols/dht/dht_client_coverage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;
import 'dart:typed_data' as _i17;

import 'package:dart_ipfs/src/core/cid.dart' as _i25;
import 'package:dart_ipfs/src/core/config/ipfs_config.dart' as _i6;
import 'package:dart_ipfs/src/core/data_structures/blockstore.dart' as _i10;
import 'package:dart_ipfs/src/core/data_structures/link.dart' as _i21;
import 'package:dart_ipfs/src/core/data_structures/peer.dart' as _i22;
import 'package:dart_ipfs/src/core/ipfs_node/ipfs_node.dart' as _i2;
import 'package:dart_ipfs/src/core/ipfs_node/network_handler.dart' as _i18;
import 'package:dart_ipfs/src/core/mfs/mfs_manager.dart' as _i7;
import 'package:dart_ipfs/src/core/plugins/ipfs_plugin.dart' as _i8;
import 'package:dart_ipfs/src/core/security/security_manager.dart' as _i9;
import 'package:dart_ipfs/src/core/storage/datastore.dart' as _i12;
import 'package:dart_ipfs/src/core/types/peer_id.dart' as _i26;
import 'package:dart_ipfs/src/network/router.dart' as _i4;
import 'package:dart_ipfs/src/proto/generated/dht/common_red_black_tree.pb.dart'
    as _i24;
import 'package:dart_ipfs/src/proto/generated/dht/ipfs_node_network_events.pb.dart'
    as _i19;
import 'package:dart_ipfs/src/protocols/dht/dht_client.dart' as _i11;
import 'package:dart_ipfs/src/protocols/dht/dht_handler.dart' as _i23;
import 'package:dart_ipfs/src/protocols/dht/interface_dht_handler.dart' as _i13;
import 'package:dart_ipfs/src/protocols/pubsub/pubsub_message.dart' as _i20;
import 'package:dart_ipfs/src/transport/circuit_relay_client.dart' as _i5;
import 'package:dart_ipfs/src/transport/router_events.dart' as _i16;
import 'package:dart_ipfs/src/transport/router_interface.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIPFSNode_0 extends _i1.SmartFake implements _i2.IPFSNode {
  _FakeIPFSNode_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouterInterface_1 extends _i1.SmartFake
    implements _i3.RouterInterface {
  _FakeRouterInterface_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouter_2 extends _i1.SmartFake implements _i4.Router {
  _FakeRouter_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCircuitRelayClient_3 extends _i1.SmartFake
    implements _i5.CircuitRelayClient {
  _FakeCircuitRelayClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPFSConfig_4 extends _i1.SmartFake implements _i6.IPFSConfig {
  _FakeIPFSConfig_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMFSManager_5 extends _i1.SmartFake implements _i7.MFSManager {
  _FakeMFSManager_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePluginManager_6 extends _i1.SmartFake implements _i8.PluginManager {
  _FakePluginManager_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecurityManager_7 extends _i1.SmartFake
    implements _i9.SecurityManager {
  _FakeSecurityManager_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBlockStore_8 extends _i1.SmartFake implements _i10.BlockStore {
  _FakeBlockStore_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDHTClient_9 extends _i1.SmartFake implements _i11.DHTClient {
  _FakeDHTClient_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatastore_10 extends _i1.SmartFake implements _i12.Datastore {
  _FakeDatastore_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValue_11 extends _i1.SmartFake implements _i13.Value {
  _FakeValue_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RouterInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterInterface extends _i1.Mock implements _i3.RouterInterface {
  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  bool get hasStarted =>
      (super.noSuchMethod(
            Invocation.getter(#hasStarted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Set<String> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  _i15.Stream<_i16.ConnectionEvent> get connectionEvents =>
      (super.noSuchMethod(
            Invocation.getter(#connectionEvents),
            returnValue: _i15.Stream<_i16.ConnectionEvent>.empty(),
            returnValueForMissingStub:
                _i15.Stream<_i16.ConnectionEvent>.empty(),
          )
          as _i15.Stream<_i16.ConnectionEvent>);

  @override
  _i15.Stream<_i16.MessageEvent> get messageEvents =>
      (super.noSuchMethod(
            Invocation.getter(#messageEvents),
            returnValue: _i15.Stream<_i16.MessageEvent>.empty(),
            returnValueForMissingStub: _i15.Stream<_i16.MessageEvent>.empty(),
          )
          as _i15.Stream<_i16.MessageEvent>);

  @override
  List<String> get listeningAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#listeningAddresses),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i15.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> connect(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [multiaddress]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> disconnect(String? peerIdOrMultiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [peerIdOrMultiaddress]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  List<String> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool isConnectedPeer(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#isConnectedPeer, [peerIdStr]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i15.Future<void> sendMessage(
    String? peerIdStr,
    _i17.Uint8List? message, {
    String? protocolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [peerIdStr, message],
              {#protocolId: protocolId},
            ),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i17.Uint8List?> sendRequest(
    String? peerId,
    String? protocolId,
    _i17.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i15.Future<_i17.Uint8List?>.value(),
            returnValueForMissingStub: _i15.Future<_i17.Uint8List?>.value(),
          )
          as _i15.Future<_i17.Uint8List?>);

  @override
  _i15.Stream<_i17.Uint8List> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i15.Stream<_i17.Uint8List>.empty(),
            returnValueForMissingStub: _i15.Stream<_i17.Uint8List>.empty(),
          )
          as _i15.Stream<_i17.Uint8List>);

  @override
  void registerProtocolHandler(
    String? protocolId,
    void Function(_i16.NetworkPacket)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#registerProtocolHandler, [protocolId, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void removeMessageHandler(String? protocolId) => super.noSuchMethod(
    Invocation.method(#removeMessageHandler, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  void registerProtocol(String? protocolId) => super.noSuchMethod(
    Invocation.method(#registerProtocol, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> broadcastMessage(
    String? protocolId,
    _i17.Uint8List? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastMessage, [protocolId, message]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void emitEvent(String? topic, _i17.Uint8List? data) => super.noSuchMethod(
    Invocation.method(#emitEvent, [topic, data]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#onEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void offEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#offEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  Object? parseMultiaddr(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#parseMultiaddr, [multiaddr]),
            returnValueForMissingStub: null,
          )
          as Object?);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);
}

/// A class which mocks [NetworkHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkHandler extends _i1.Mock implements _i18.NetworkHandler {
  @override
  _i2.IPFSNode get ipfsNode =>
      (super.noSuchMethod(
            Invocation.getter(#ipfsNode),
            returnValue: _FakeIPFSNode_0(this, Invocation.getter(#ipfsNode)),
            returnValueForMissingStub: _FakeIPFSNode_0(
              this,
              Invocation.getter(#ipfsNode),
            ),
          )
          as _i2.IPFSNode);

  @override
  _i3.RouterInterface get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
            returnValueForMissingStub: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i3.RouterInterface);

  @override
  _i15.Stream<_i19.NetworkEvent> get networkEvents =>
      (super.noSuchMethod(
            Invocation.getter(#networkEvents),
            returnValue: _i15.Stream<_i19.NetworkEvent>.empty(),
            returnValueForMissingStub: _i15.Stream<_i19.NetworkEvent>.empty(),
          )
          as _i15.Stream<_i19.NetworkEvent>);

  @override
  _i4.Router get dhtRouter =>
      (super.noSuchMethod(
            Invocation.getter(#dhtRouter),
            returnValue: _FakeRouter_2(this, Invocation.getter(#dhtRouter)),
            returnValueForMissingStub: _FakeRouter_2(
              this,
              Invocation.getter(#dhtRouter),
            ),
          )
          as _i4.Router);

  @override
  _i5.CircuitRelayClient get circuitRelayClient =>
      (super.noSuchMethod(
            Invocation.getter(#circuitRelayClient),
            returnValue: _FakeCircuitRelayClient_3(
              this,
              Invocation.getter(#circuitRelayClient),
            ),
            returnValueForMissingStub: _FakeCircuitRelayClient_3(
              this,
              Invocation.getter(#circuitRelayClient),
            ),
          )
          as _i5.CircuitRelayClient);

  @override
  _i6.IPFSConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeIPFSConfig_4(this, Invocation.getter(#config)),
            returnValueForMissingStub: _FakeIPFSConfig_4(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i6.IPFSConfig);

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  set ipfsNode(_i2.IPFSNode? value) => super.noSuchMethod(
    Invocation.setter(#ipfsNode, value),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> connectToPeer(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connectToPeer, [multiaddress]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> disconnectFromPeer(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromPeer, [multiaddress]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<List<String>> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: _i15.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i15.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i15.Future<List<String>>);

  @override
  _i15.Future<void> sendMessage(String? peerId, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [peerId, message]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Stream<String> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i15.Stream<String>.empty(),
            returnValueForMissingStub: _i15.Stream<String>.empty(),
          )
          as _i15.Stream<String>);

  @override
  void setIpfsNode(_i2.IPFSNode? node) => super.noSuchMethod(
    Invocation.method(#setIpfsNode, [node]),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<_i17.Uint8List?> sendRequest(
    String? peerId,
    String? protocolId,
    _i17.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i15.Future<_i17.Uint8List?>.value(),
            returnValueForMissingStub: _i15.Future<_i17.Uint8List?>.value(),
          )
          as _i15.Future<_i17.Uint8List?>);

  @override
  _i15.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<bool> canConnectDirectly(String? peerAddress) =>
      (super.noSuchMethod(
            Invocation.method(#canConnectDirectly, [peerAddress]),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> testDialback() =>
      (super.noSuchMethod(
            Invocation.method(#testDialback, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);
}

/// A class which mocks [IPFSNode].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPFSNode extends _i1.Mock implements _i2.IPFSNode {
  @override
  _i2.NodeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i2.NodeState.stopped,
            returnValueForMissingStub: _i2.NodeState.stopped,
          )
          as _i2.NodeState);

  @override
  _i7.MFSManager get mfs =>
      (super.noSuchMethod(
            Invocation.getter(#mfs),
            returnValue: _FakeMFSManager_5(this, Invocation.getter(#mfs)),
            returnValueForMissingStub: _FakeMFSManager_5(
              this,
              Invocation.getter(#mfs),
            ),
          )
          as _i7.MFSManager);

  @override
  _i8.PluginManager get plugins =>
      (super.noSuchMethod(
            Invocation.getter(#plugins),
            returnValue: _FakePluginManager_6(
              this,
              Invocation.getter(#plugins),
            ),
            returnValueForMissingStub: _FakePluginManager_6(
              this,
              Invocation.getter(#plugins),
            ),
          )
          as _i8.PluginManager);

  @override
  _i9.SecurityManager get securityManager =>
      (super.noSuchMethod(
            Invocation.getter(#securityManager),
            returnValue: _FakeSecurityManager_7(
              this,
              Invocation.getter(#securityManager),
            ),
            returnValueForMissingStub: _FakeSecurityManager_7(
              this,
              Invocation.getter(#securityManager),
            ),
          )
          as _i9.SecurityManager);

  @override
  bool get isRunning =>
      (super.noSuchMethod(
            Invocation.getter(#isRunning),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get peerId =>
      (super.noSuchMethod(
            Invocation.getter(#peerId),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerId),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerId),
            ),
          )
          as String);

  @override
  _i15.Stream<Map<String, dynamic>> get bandwidthMetrics =>
      (super.noSuchMethod(
            Invocation.getter(#bandwidthMetrics),
            returnValue: _i15.Stream<Map<String, dynamic>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<Map<String, dynamic>>.empty(),
          )
          as _i15.Stream<Map<String, dynamic>>);

  @override
  List<String> get addresses =>
      (super.noSuchMethod(
            Invocation.getter(#addresses),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i10.BlockStore get blockStore =>
      (super.noSuchMethod(
            Invocation.getter(#blockStore),
            returnValue: _FakeBlockStore_8(
              this,
              Invocation.getter(#blockStore),
            ),
            returnValueForMissingStub: _FakeBlockStore_8(
              this,
              Invocation.getter(#blockStore),
            ),
          )
          as _i10.BlockStore);

  @override
  _i11.DHTClient get dhtClient =>
      (super.noSuchMethod(
            Invocation.getter(#dhtClient),
            returnValue: _FakeDHTClient_9(this, Invocation.getter(#dhtClient)),
            returnValueForMissingStub: _FakeDHTClient_9(
              this,
              Invocation.getter(#dhtClient),
            ),
          )
          as _i11.DHTClient);

  @override
  _i15.Future<List<String>> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: _i15.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i15.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i15.Future<List<String>>);

  @override
  _i15.Future<String> get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i15.Future<String>.value(
              _i14.dummyValue<String>(this, Invocation.getter(#publicKey)),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i14.dummyValue<String>(this, Invocation.getter(#publicKey)),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<List<String>> get pinnedCids =>
      (super.noSuchMethod(
            Invocation.getter(#pinnedCids),
            returnValue: _i15.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i15.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i15.Future<List<String>>);

  @override
  _i15.Stream<_i20.PubSubMessage> get pubsubMessages =>
      (super.noSuchMethod(
            Invocation.getter(#pubsubMessages),
            returnValue: _i15.Stream<_i20.PubSubMessage>.empty(),
            returnValueForMissingStub: _i15.Stream<_i20.PubSubMessage>.empty(),
          )
          as _i15.Stream<_i20.PubSubMessage>);

  @override
  _i12.Datastore get datastore =>
      (super.noSuchMethod(
            Invocation.getter(#datastore),
            returnValue: _FakeDatastore_10(this, Invocation.getter(#datastore)),
            returnValueForMissingStub: _FakeDatastore_10(
              this,
              Invocation.getter(#datastore),
            ),
          )
          as _i12.Datastore);

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  _i15.Stream<String> get onNewContent =>
      (super.noSuchMethod(
            Invocation.getter(#onNewContent),
            returnValue: _i15.Stream<String>.empty(),
            returnValueForMissingStub: _i15.Stream<String>.empty(),
          )
          as _i15.Stream<String>);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i15.Future<_i17.Uint8List?> cat(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#cat, [cid]),
            returnValue: _i15.Future<_i17.Uint8List?>.value(),
            returnValueForMissingStub: _i15.Future<_i17.Uint8List?>.value(),
          )
          as _i15.Future<_i17.Uint8List?>);

  @override
  _i15.Future<void> connectToPeer(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#connectToPeer, [multiaddr]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> disconnectFromPeer(String? peerIdOrAddr) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromPeer, [peerIdOrAddr]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String> resolveIPNS(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#resolveIPNS, [name]),
            returnValue: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [name]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [name]),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<void> subscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [topic]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> unsubscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [topic]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> publish(String? topic, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [topic, message]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> restart() =>
      (super.noSuchMethod(
            Invocation.method(#restart, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String> addFile(_i17.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#addFile, [data]),
            returnValue: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#addFile, [data]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#addFile, [data]),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<String> addFileStream(_i15.Stream<List<int>>? dataStream) =>
      (super.noSuchMethod(
            Invocation.method(#addFileStream, [dataStream]),
            returnValue: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#addFileStream, [dataStream]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#addFileStream, [dataStream]),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<String> addDirectory(Map<String, dynamic>? directoryContent) =>
      (super.noSuchMethod(
            Invocation.method(#addDirectory, [directoryContent]),
            returnValue: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#addDirectory, [directoryContent]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#addDirectory, [directoryContent]),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  void setGatewayMode(_i2.GatewayMode? mode, {String? customUrl}) =>
      super.noSuchMethod(
        Invocation.method(#setGatewayMode, [mode], {#customUrl: customUrl}),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Future<_i17.Uint8List?> get(String? cid, {String? path = ''}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [cid], {#path: path}),
            returnValue: _i15.Future<_i17.Uint8List?>.value(),
            returnValueForMissingStub: _i15.Future<_i17.Uint8List?>.value(),
          )
          as _i15.Future<_i17.Uint8List?>);

  @override
  _i15.Future<List<_i21.Link>> ls(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#ls, [cid]),
            returnValue: _i15.Future<List<_i21.Link>>.value(<_i21.Link>[]),
            returnValueForMissingStub: _i15.Future<List<_i21.Link>>.value(
              <_i21.Link>[],
            ),
          )
          as _i15.Future<List<_i21.Link>>);

  @override
  _i15.Future<void> pin(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#pin, [cid]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<bool> unpin(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#unpin, [cid]),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> publishIPNS(String? cid, {required String? keyName}) =>
      (super.noSuchMethod(
            Invocation.method(#publishIPNS, [cid], {#keyName: keyName}),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> importCAR(_i17.Uint8List? carFile) =>
      (super.noSuchMethod(
            Invocation.method(#importCAR, [carFile]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i17.Uint8List> exportCAR(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#exportCAR, [cid]),
            returnValue: _i15.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
            returnValueForMissingStub: _i15.Future<_i17.Uint8List>.value(
              _i17.Uint8List(0),
            ),
          )
          as _i15.Future<_i17.Uint8List>);

  @override
  _i15.Future<List<String>> findProviders(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i15.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i15.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i15.Future<List<String>>);

  @override
  _i15.Future<void> requestBlock(String? cid, _i22.Peer? peer) =>
      (super.noSuchMethod(
            Invocation.method(#requestBlock, [cid, peer]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String> resolveDNSLink(String? domainName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDNSLink, [domainName]),
            returnValue: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveDNSLink, [domainName]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveDNSLink, [domainName]),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<Map<String, dynamic>> getHealthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getHealthStatus, []),
            returnValue: _i15.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i15.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i15.Future<Map<String, dynamic>>);
}

/// A class which mocks [DHTHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockDHTHandler extends _i1.Mock implements _i23.DHTHandler {
  @override
  _i11.DHTClient get dhtClient =>
      (super.noSuchMethod(
            Invocation.getter(#dhtClient),
            returnValue: _FakeDHTClient_9(this, Invocation.getter(#dhtClient)),
            returnValueForMissingStub: _FakeDHTClient_9(
              this,
              Invocation.getter(#dhtClient),
            ),
          )
          as _i11.DHTClient);

  @override
  _i3.RouterInterface get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
            returnValueForMissingStub: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i3.RouterInterface);

  @override
  _i12.Datastore get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeDatastore_10(this, Invocation.getter(#storage)),
            returnValueForMissingStub: _FakeDatastore_10(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i12.Datastore);

  @override
  set dhtClient(_i11.DHTClient? value) => super.noSuchMethod(
    Invocation.setter(#dhtClient, value),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<List<_i24.V_PeerInfo>> findProviders(_i25.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i15.Future<List<_i24.V_PeerInfo>>.value(
              <_i24.V_PeerInfo>[],
            ),
            returnValueForMissingStub: _i15.Future<List<_i24.V_PeerInfo>>.value(
              <_i24.V_PeerInfo>[],
            ),
          )
          as _i15.Future<List<_i24.V_PeerInfo>>);

  @override
  _i15.Future<void> putValue(_i13.Key? key, _i13.Value? value) =>
      (super.noSuchMethod(
            Invocation.method(#putValue, [key, value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i13.Value> getValue(_i13.Key? key) =>
      (super.noSuchMethod(
            Invocation.method(#getValue, [key]),
            returnValue: _i15.Future<_i13.Value>.value(
              _FakeValue_11(this, Invocation.method(#getValue, [key])),
            ),
            returnValueForMissingStub: _i15.Future<_i13.Value>.value(
              _FakeValue_11(this, Invocation.method(#getValue, [key])),
            ),
          )
          as _i15.Future<_i13.Value>);

  @override
  _i15.Future<String> resolveIPNS(String? ipnsName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveIPNS, [ipnsName]),
            returnValue: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [ipnsName]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [ipnsName]),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<void> publishIPNS(String? cid, {required String? keyName}) =>
      (super.noSuchMethod(
            Invocation.method(#publishIPNS, [cid], {#keyName: keyName}),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  bool isValidCID(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#isValidCID, [cid]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isValidPeerID(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#isValidPeerID, [peerId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String? extractCIDFromResponse(String? responseBody) =>
      (super.noSuchMethod(
            Invocation.method(#extractCIDFromResponse, [responseBody]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i15.Future<List<_i24.V_PeerInfo>> findPeer(_i26.PeerId? id) =>
      (super.noSuchMethod(
            Invocation.method(#findPeer, [id]),
            returnValue: _i15.Future<List<_i24.V_PeerInfo>>.value(
              <_i24.V_PeerInfo>[],
            ),
            returnValueForMissingStub: _i15.Future<List<_i24.V_PeerInfo>>.value(
              <_i24.V_PeerInfo>[],
            ),
          )
          as _i15.Future<List<_i24.V_PeerInfo>>);

  @override
  _i15.Future<void> provide(_i25.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#provide, [cid]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> handleRoutingTableUpdate(_i24.V_PeerInfo? peer) =>
      (super.noSuchMethod(
            Invocation.method(#handleRoutingTableUpdate, [peer]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> handleProvideRequest(
    _i25.CID? cid,
    _i26.PeerId? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleProvideRequest, [cid, provider]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String?> resolveDNSLink(String? domainName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDNSLink, [domainName]),
            returnValue: _i15.Future<String?>.value(),
            returnValueForMissingStub: _i15.Future<String?>.value(),
          )
          as _i15.Future<String?>);

  @override
  _i15.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i15.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i15.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i15.Future<Map<String, dynamic>>);
}

/// A class which mocks [Datastore].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatastore extends _i1.Mock implements _i12.Datastore {
  @override
  _i15.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> put(_i12.Key? key, _i17.Uint8List? value) =>
      (super.noSuchMethod(
            Invocation.method(#put, [key, value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i17.Uint8List?> get(_i12.Key? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _i15.Future<_i17.Uint8List?>.value(),
            returnValueForMissingStub: _i15.Future<_i17.Uint8List?>.value(),
          )
          as _i15.Future<_i17.Uint8List?>);

  @override
  _i15.Future<bool> has(_i12.Key? key) =>
      (super.noSuchMethod(
            Invocation.method(#has, [key]),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> delete(_i12.Key? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Stream<_i12.QueryEntry> query(_i12.Query? q) =>
      (super.noSuchMethod(
            Invocation.method(#query, [q]),
            returnValue: _i15.Stream<_i12.QueryEntry>.empty(),
            returnValueForMissingStub: _i15.Stream<_i12.QueryEntry>.empty(),
          )
          as _i15.Stream<_i12.QueryEntry>);

  @override
  _i15.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}
