// Mocks generated by Mockito from annotations
// in dart_ipfs/test/protocols/dht/kademlia_routing_adapter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i8;

import 'package:dart_ipfs/src/core/types/peer_id.dart' as _i4;
import 'package:dart_ipfs/src/proto/generated/dht/common_red_black_tree.pb.dart'
    as _i9;
import 'package:dart_ipfs/src/protocols/dht/connection_statistics.dart' as _i5;
import 'package:dart_ipfs/src/protocols/dht/dht_client.dart' as _i2;
import 'package:dart_ipfs/src/protocols/dht/kademlia_routing_table.dart' as _i3;
import 'package:dart_ipfs/src/protocols/dht/kademlia_tree/kademlia_tree_node.dart'
    as _i7;
import 'package:dart_ipfs/src/protocols/dht/red_black_tree.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDHTClient_0 extends _i1.SmartFake implements _i2.DHTClient {
  _FakeDHTClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KademliaRoutingTable].
///
/// See the documentation for Mockito's code generation for more information.
class MockKademliaRoutingTable extends _i1.Mock
    implements _i3.KademliaRoutingTable {
  MockKademliaRoutingTable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DHTClient get dhtClient =>
      (super.noSuchMethod(
            Invocation.getter(#dhtClient),
            returnValue: _FakeDHTClient_0(this, Invocation.getter(#dhtClient)),
          )
          as _i2.DHTClient);

  @override
  int get peerCount =>
      (super.noSuchMethod(Invocation.getter(#peerCount), returnValue: 0)
          as int);

  @override
  bool get isStopped =>
      (super.noSuchMethod(Invocation.getter(#isStopped), returnValue: false)
          as bool);

  @override
  Map<_i4.PeerId, _i5.ConnectionStatistics> get connectionStats =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStats),
            returnValue: <_i4.PeerId, _i5.ConnectionStatistics>{},
          )
          as Map<_i4.PeerId, _i5.ConnectionStatistics>);

  @override
  Map<_i4.PeerId, DateTime> get lastSeen =>
      (super.noSuchMethod(
            Invocation.getter(#lastSeen),
            returnValue: <_i4.PeerId, DateTime>{},
          )
          as Map<_i4.PeerId, DateTime>);

  @override
  List<_i6.RedBlackTree<_i4.PeerId, _i7.KademliaTreeNode>> get buckets =>
      (super.noSuchMethod(
            Invocation.getter(#buckets),
            returnValue: <_i6.RedBlackTree<_i4.PeerId, _i7.KademliaTreeNode>>[],
          )
          as List<_i6.RedBlackTree<_i4.PeerId, _i7.KademliaTreeNode>>);

  @override
  set dhtClient(_i2.DHTClient? value) => super.noSuchMethod(
    Invocation.setter(#dhtClient, value),
    returnValueForMissingStub: null,
  );

  @override
  void initialize(_i2.DHTClient? client) => super.noSuchMethod(
    Invocation.method(#initialize, [client]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> addPeer(
    _i4.PeerId? peerId,
    _i4.PeerId? associatedPeerId, {
    String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addPeer,
              [peerId, associatedPeerId],
              {#address: address},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void removePeer(_i4.PeerId? peerId) => super.noSuchMethod(
    Invocation.method(#removePeer, [peerId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.PeerId? getAssociatedPeer(_i4.PeerId? peerId) =>
      (super.noSuchMethod(Invocation.method(#getAssociatedPeer, [peerId]))
          as _i4.PeerId?);

  @override
  bool containsPeer(_i4.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#containsPeer, [peerId]),
            returnValue: false,
          )
          as bool);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void stop() => super.noSuchMethod(
    Invocation.method(#stop, []),
    returnValueForMissingStub: null,
  );

  @override
  BigInt calculateDistance(_i4.PeerId? a, _i4.PeerId? b) =>
      (super.noSuchMethod(
            Invocation.method(#calculateDistance, [a, b]),
            returnValue: BigInt.zero,
          )
          as BigInt);

  @override
  List<_i4.PeerId> findClosestPeers(_i4.PeerId? target, int? k) =>
      (super.noSuchMethod(
            Invocation.method(#findClosestPeers, [target, k]),
            returnValue: <_i4.PeerId>[],
          )
          as List<_i4.PeerId>);

  @override
  _i8.Future<List<_i4.PeerId>> nodeLookup(_i4.PeerId? target) =>
      (super.noSuchMethod(
            Invocation.method(#nodeLookup, [target]),
            returnValue: _i8.Future<List<_i4.PeerId>>.value(<_i4.PeerId>[]),
          )
          as _i8.Future<List<_i4.PeerId>>);

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void addPeerToBucket(_i4.PeerId? peerId, _i4.PeerId? associatedPeerId) =>
      super.noSuchMethod(
        Invocation.method(#addPeerToBucket, [peerId, associatedPeerId]),
        returnValueForMissingStub: null,
      );

  @override
  void removePeerFromBucket(_i4.PeerId? peerId) => super.noSuchMethod(
    Invocation.method(#removePeerFromBucket, [peerId]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> updatePeer(_i9.V_PeerInfo? peer) =>
      (super.noSuchMethod(
            Invocation.method(#updatePeer, [peer]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addKeyProvider(
    _i4.PeerId? key,
    _i4.PeerId? provider,
    DateTime? timestamp,
  ) => super.noSuchMethod(
    Invocation.method(#addKeyProvider, [key, provider, timestamp]),
    returnValueForMissingStub: null,
  );

  @override
  void updateKeyProviderTimestamp(
    _i4.PeerId? key,
    _i4.PeerId? provider,
    DateTime? timestamp,
  ) => super.noSuchMethod(
    Invocation.method(#updateKeyProviderTimestamp, [key, provider, timestamp]),
    returnValueForMissingStub: null,
  );

  @override
  int distance(_i4.PeerId? a, _i4.PeerId? b) =>
      (super.noSuchMethod(Invocation.method(#distance, [a, b]), returnValue: 0)
          as int);

  @override
  _i8.Future<bool> pingPeer(_i4.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#pingPeer, [peerId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}
