// Mocks generated by Mockito 5.4.6 from annotations
// in dart_ipfs/test/core/ipld/codecs/codecs_coverage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i5;

import 'package:dart_ipfs/src/utils/private_key.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:pointycastle/export.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeECPublicKey_0 extends _i1.SmartFake implements _i2.ECPublicKey {
  _FakeECPublicKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeECPrivateKey_1 extends _i1.SmartFake implements _i2.ECPrivateKey {
  _FakeECPrivateKey_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IPFSPrivateKey].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPFSPrivateKey extends _i1.Mock implements _i3.IPFSPrivateKey {
  MockIPFSPrivateKey() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get algorithm =>
      (super.noSuchMethod(
            Invocation.getter(#algorithm),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#algorithm),
            ),
          )
          as String);

  @override
  _i2.ECPublicKey get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _FakeECPublicKey_0(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as _i2.ECPublicKey);

  @override
  _i2.ECPrivateKey get privateKey =>
      (super.noSuchMethod(
            Invocation.getter(#privateKey),
            returnValue: _FakeECPrivateKey_1(
              this,
              Invocation.getter(#privateKey),
            ),
          )
          as _i2.ECPrivateKey);

  @override
  _i5.Uint8List get publicKeyBytes =>
      (super.noSuchMethod(
            Invocation.getter(#publicKeyBytes),
            returnValue: _i5.Uint8List(0),
          )
          as _i5.Uint8List);

  @override
  _i5.Uint8List sign(_i5.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#sign, [data]),
            returnValue: _i5.Uint8List(0),
          )
          as _i5.Uint8List);

  @override
  bool verify(
    _i5.Uint8List? data,
    _i5.Uint8List? signature, {
    String? algorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #verify,
              [data, signature],
              {#algorithm: algorithm},
            ),
            returnValue: false,
          )
          as bool);
}
