// lib/src/services/gateway/acme_persistence.dart
import 'dart:convert';
import 'dart:io';

import 'package:pointycastle/export.dart' as pc;

import '../../core/config/gateway_config.dart';
import '../../utils/logger.dart';

/// Manages persistent storage for ACME account keys and certificates.
///
/// This class provides file-based storage for:
/// - ACME account keys (RSA private keys used for ACME protocol authentication)
/// - Certificate chains (PEM-encoded certificates from ACME)
/// - Certificate private keys (PEM-encoded keys matching the certificates)
/// - Certificate metadata (expiry dates, domain info)
///
/// Storage paths can be configured via [GatewayConfig] or default to a
/// data directory relative to the current working directory.
class AcmePersistence {
  /// Creates an ACME persistence manager with the given [config].
  ///
  /// If storage paths are not configured in [config], default paths are used:
  /// - Account key: `{baseDirectory}/account_key.pem`
  /// - Certificate: `{baseDirectory}/certificate.pem`
  /// - Private key: `{baseDirectory}/private_key.pem`
  /// - Metadata: `{baseDirectory}/metadata.json`
  ///
  /// [baseDirectory] defaults to `./data/acme` and is mainly exposed for
  /// testing so that tests do not rely on the global working directory.
  AcmePersistence(this.config, {String? baseDirectory})
    : _baseDirectory = baseDirectory ?? _defaultDataDir,
      _logger = Logger('AcmePersistence');

  /// Gateway configuration containing storage path settings.
  final GatewayConfig config;

  final Logger _logger;

  /// Default data directory for ACME files.
  static const String _defaultDataDir = './data/acme';

  final String _baseDirectory;

  /// Gets the account key storage path.
  String get _accountKeyPath =>
      config.autoTlsAccountKeyPath ?? '$_baseDirectory/account_key.pem';

  /// Gets the certificate chain storage path.
  String get _certificatePath =>
      config.autoTlsCertificatePath ?? '$_baseDirectory/certificate.pem';

  /// Gets the certificate private key storage path.
  String get _privateKeyPath =>
      config.autoTlsPrivateKeyPath ?? '$_baseDirectory/private_key.pem';

  /// Gets the metadata storage path.
  String get _metadataPath => '$_baseDirectory/metadata.json';

  /// Ensures the storage directory exists.
  Future<void> _ensureDirectory() async {
    final dir = Directory(_baseDirectory);
    if (!dir.existsSync()) {
      await dir.create(recursive: true);
      _logger.info('Created ACME storage directory: $_baseDirectory');
    }
  }

  /// Loads the ACME account key from storage.
  ///
  /// Returns `null` if no account key exists or if parsing fails.
  /// When parsing fails, a new key will be generated by the ACME client.
  Future<pc.RSAPrivateKey?> loadAccountKey() async {
    // This method is deprecated in favor of loadAccountKeyPem
    // since we can't reliably parse PEM back to RSAPrivateKey without DER parsing
    return null;
  }

  /// Saves the ACME account key to storage.
  ///
  /// This method is deprecated in favor of saveAccountKeyPem.
  Future<void> saveAccountKey(pc.RSAPrivateKey key) async {
    // This method is deprecated in favor of saveAccountKeyPem
    throw UnimplementedError('Use saveAccountKeyPem instead');
  }

  /// Loads the certificate chain from storage.
  ///
  /// Returns `null` if no certificate exists.
  Future<String?> loadCertificate() async {
    try {
      final file = File(_certificatePath);
      if (!file.existsSync()) {
        _logger.info('No certificate found at $_certificatePath');
        return null;
      }

      final pem = await file.readAsString();
      _logger.info('Loaded certificate from $_certificatePath');
      return pem;
    } catch (e, stackTrace) {
      _logger.error('Failed to load certificate', e, stackTrace);
      return null;
    }
  }

  /// Loads the certificate private key from storage.
  ///
  /// Returns `null` if no private key exists.
  Future<String?> loadPrivateKey() async {
    try {
      final file = File(_privateKeyPath);
      if (!file.existsSync()) {
        _logger.info('No private key found at $_privateKeyPath');
        return null;
      }

      final pem = await file.readAsString();
      _logger.info('Loaded private key from $_privateKeyPath');
      return pem;
    } catch (e, stackTrace) {
      _logger.error('Failed to load private key', e, stackTrace);
      return null;
    }
  }

  /// Saves the certificate chain and private key to storage.
  ///
  /// Also saves metadata including the expiry date and domains.
  Future<void> saveCertificate({
    required String certificatePem,
    required String privateKeyPem,
    required DateTime notAfter,
    required List<String> domains,
  }) async {
    try {
      await _ensureDirectory();

      // Save certificate
      final certFile = File(_certificatePath);
      await certFile.writeAsString(certificatePem);
      _logger.info('Saved certificate to $_certificatePath');

      // Save private key
      final keyFile = File(_privateKeyPath);
      await keyFile.writeAsString(privateKeyPem);
      _logger.info('Saved private key to $_privateKeyPath');

      // Save metadata
      final metadata = {
        'notAfter': notAfter.toIso8601String(),
        'domains': domains,
        'savedAt': DateTime.now().toIso8601String(),
      };
      final metadataFile = File(_metadataPath);
      await metadataFile.writeAsString(jsonEncode(metadata));
      _logger.info('Saved certificate metadata to $_metadataPath');
    } catch (e, stackTrace) {
      _logger.error('Failed to save certificate', e, stackTrace);
      rethrow;
    }
  }

  /// Loads certificate metadata from storage.
  ///
  /// Returns `null` if no metadata exists.
  Future<Map<String, dynamic>?> loadMetadata() async {
    try {
      final file = File(_metadataPath);
      if (!file.existsSync()) {
        return null;
      }

      final json = await file.readAsString();
      return jsonDecode(json) as Map<String, dynamic>;
    } catch (e, stackTrace) {
      _logger.warning('Failed to load certificate metadata', e, stackTrace);
      return null;
    }
  }

  /// Deletes all ACME files from storage.
  ///
  /// This is useful for resetting the ACME account or when switching domains.
  Future<void> deleteAll() async {
    try {
      final files = [
        File(_accountKeyPath),
        File(_certificatePath),
        File(_privateKeyPath),
        File(_metadataPath),
      ];

      for (final file in files) {
        if (file.existsSync()) {
          await file.delete();
          _logger.info('Deleted ${file.path}');
        }
      }

      // Try to remove the directory if empty
      final dir = Directory(_baseDirectory);
      if (dir.existsSync()) {
        try {
          dir.deleteSync();
        } catch (e) {
          // Directory not empty or other error, ignore
        }
      }

      _logger.info('Deleted all ACME persistence files');
    } catch (e, stackTrace) {
      _logger.error('Failed to delete ACME files', e, stackTrace);
      rethrow;
    }
  }

  /// Checks if a valid certificate exists and is not expired.
  ///
  /// Returns `true` if a certificate exists and has not expired.
  Future<bool> hasValidCertificate() async {
    final cert = await loadCertificate();
    if (cert == null) return false;

    final metadata = await loadMetadata();
    if (metadata == null) return false;

    final notAfterStr = metadata['notAfter'] as String?;
    if (notAfterStr == null) return false;

    final notAfter = DateTime.parse(notAfterStr);
    return DateTime.now().isBefore(notAfter);
  }

  /// Checks if a certificate needs renewal based on the configured threshold.
  ///
  /// Returns `true` if the certificate exists but is within the renewal threshold
  /// days of expiry, or if the certificate is expired.
  Future<bool> needsRenewal() async {
    final metadata = await loadMetadata();
    if (metadata == null) return true; // No certificate, needs issuance

    final notAfterStr = metadata['notAfter'] as String?;
    if (notAfterStr == null) return true;

    final notAfter = DateTime.parse(notAfterStr);
    final now = DateTime.now();
    final threshold = Duration(days: config.autoTlsRenewalThresholdDays);

    // Renew if expired or within threshold
    return now.isAfter(notAfter.subtract(threshold));
  }

  /// Saves the ACME account key to storage.
  ///
  /// Note: This uses the PEM encoding from AcmeClient._rsaPrivateKeyToPem.
  Future<void> saveAccountKeyPem(String pem) async {
    try {
      await _ensureDirectory();
      final file = File(_accountKeyPath);
      await file.writeAsString(pem);
      _logger.info('Saved ACME account key to $_accountKeyPath');
    } catch (e, stackTrace) {
      _logger.error('Failed to save ACME account key', e, stackTrace);
      rethrow;
    }
  }

  /// Loads the ACME account key as PEM string from storage.
  ///
  /// Returns `null` if no account key exists.
  Future<String?> loadAccountKeyPem() async {
    try {
      final file = File(_accountKeyPath);
      if (!file.existsSync()) {
        _logger.info('No ACME account key found at $_accountKeyPath');
        return null;
      }

      final pem = await file.readAsString();
      _logger.info('Loaded ACME account key PEM from $_accountKeyPath');
      return pem;
    } catch (e, stackTrace) {
      _logger.warning('Failed to load ACME account key PEM', e, stackTrace);
      return null;
    }
  }
}
