import 'dart:async';
import 'data_channel_stream.dart';
import 'peer_connection_stub.dart'
    if (dart.library.js_interop) 'peer_connection_web.dart'
    if (dart.library.io) 'peer_connection_io.dart';

/// Abstract interface for WebRTC PeerConnections.
abstract class PeerConnection {
  /// Sets the remote description for this connection.
  Future<void> setRemoteDescription(String type, String sdp);

  /// Creates an SDP offer.
  Future<RTCSessionDescriptionInit> createOffer();

  /// Creates an SDP answer.
  Future<RTCSessionDescriptionInit> createAnswer();

  /// Sets the local description for this connection.
  Future<void> setLocalDescription(RTCSessionDescriptionInit description);

  /// Adds an ICE candidate to the connection.
  Future<void> addIceCandidate(RTCIceCandidateInit candidate);

  /// Stream of ICE candidates generated by the local peer.
  Stream<RTCIceCandidateInit> get onIceCandidate;

  /// Stream of incoming data channels.
  Stream<DataChannelStream> get onDataChannel;

  /// Creates a new data channel with the given label.
  Future<DataChannelStream> createDataChannel(String label);

  /// Closes the peer connection.
  Future<void> close();

  /// The local SDP description.
  String? get localDescriptionSdp;

  /// The remote SDP description.
  String? get remoteDescriptionSdp;
}

/// Initialization parameters for an [RTCSessionDescription].
class RTCSessionDescriptionInit {
  /// The type of the session description (offer, answer, etc.).
  final String type;

  /// The SDP string.
  final String sdp;

  /// Creates a new [RTCSessionDescriptionInit].
  RTCSessionDescriptionInit(this.type, this.sdp);
}

/// Initialization parameters for an [RTCIceCandidate].
class RTCIceCandidateInit {
  /// The ICE candidate string.
  final String candidate;

  /// The SDP mid.
  final String? sdpMid;

  /// The SDP m-line index.
  final int? sdpMLineIndex;

  /// Creates a new [RTCIceCandidateInit].
  RTCIceCandidateInit(this.candidate, this.sdpMid, this.sdpMLineIndex);

  /// Converts this candidate to a JSON-compatible map.
  Map<String, dynamic> toJson() => {
    'candidate': candidate,
    'sdpMid': sdpMid,
    'sdpMLineIndex': sdpMLineIndex,
  };
}

/// Factory for creating a platform-specific [PeerConnection].
PeerConnection createPeerConnection(List<String> iceServers) =>
    createPC(iceServers);
