// Mocks generated by Mockito 5.4.6 from annotations
// in dart_ipfs/test/protocols/protocol_coordinator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dart_ipfs/src/core/cid.dart' as _i12;
import 'package:dart_ipfs/src/core/data_structures/block.dart' as _i2;
import 'package:dart_ipfs/src/core/data_structures/metadata.dart' as _i3;
import 'package:dart_ipfs/src/core/ipfs_node/ipld_handler.dart' as _i9;
import 'package:dart_ipfs/src/core/ipld/codecs/ipld_codec.dart' as _i10;
import 'package:dart_ipfs/src/core/ipld/schema/ipld_schema.dart' as _i11;
import 'package:dart_ipfs/src/core/ipld/selectors/ipld_selector.dart' as _i8;
import 'package:dart_ipfs/src/proto/generated/graphsync/graphsync.pb.dart'
    as _i7;
import 'package:dart_ipfs/src/protocols/bitswap/bitswap_handler.dart' as _i4;
import 'package:dart_ipfs/src/protocols/graphsync/graphsync_handler.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBlock_0 extends _i1.SmartFake implements _i2.Block {
  _FakeBlock_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPLDMetadata_1 extends _i1.SmartFake implements _i3.IPLDMetadata {
  _FakeIPLDMetadata_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BitswapHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockBitswapHandler extends _i1.Mock implements _i4.BitswapHandler {
  @override
  int get bandwidthSent =>
      (super.noSuchMethod(
            Invocation.getter(#bandwidthSent),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get bandwidthReceived =>
      (super.noSuchMethod(
            Invocation.getter(#bandwidthReceived),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> handleBlocks(List<_i2.Block>? blocks) =>
      (super.noSuchMethod(
            Invocation.method(#handleBlocks, [blocks]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Block>> want(
    List<String>? cids, {
    int? priority = 1,
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #want,
              [cids],
              {#priority: priority, #timeout: timeout},
            ),
            returnValue: _i5.Future<List<_i2.Block>>.value(<_i2.Block>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Block>>.value(
              <_i2.Block>[],
            ),
          )
          as _i5.Future<List<_i2.Block>>);

  @override
  _i5.Future<void> handleWantRequest(String? cidStr) =>
      (super.noSuchMethod(
            Invocation.method(#handleWantRequest, [cidStr]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Block?> wantBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#wantBlock, [cid]),
            returnValue: _i5.Future<_i2.Block?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.Block?>.value(),
          )
          as _i5.Future<_i2.Block?>);

  @override
  _i5.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [GraphsyncHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphsyncHandler extends _i1.Mock implements _i6.GraphsyncHandler {
  @override
  _i5.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i7.Block?> requestGraph(
    String? cidStr,
    _i8.IPLDSelector? selector,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestGraph, [cidStr, selector]),
            returnValue: _i5.Future<_i7.Block?>.value(),
            returnValueForMissingStub: _i5.Future<_i7.Block?>.value(),
          )
          as _i5.Future<_i7.Block?>);
}

/// A class which mocks [IPLDHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPLDHandler extends _i1.Mock implements _i9.IPLDHandler {
  @override
  bool get isRunning =>
      (super.noSuchMethod(
            Invocation.getter(#isRunning),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void registerCodec(_i10.IPLDCodec? codec) => super.noSuchMethod(
    Invocation.method(#registerCodec, [codec]),
    returnValueForMissingStub: null,
  );

  @override
  void registerSchema(_i11.IPLDSchema? schema) => super.noSuchMethod(
    Invocation.method(#registerSchema, [schema]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.Block> put(
    dynamic value, {
    String? codec = 'dag-cbor',
    String? schemaType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [value],
              {#codec: codec, #schemaType: schemaType},
            ),
            returnValue: _i5.Future<_i2.Block>.value(
              _FakeBlock_0(
                this,
                Invocation.method(
                  #put,
                  [value],
                  {#codec: codec, #schemaType: schemaType},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Block>.value(
              _FakeBlock_0(
                this,
                Invocation.method(
                  #put,
                  [value],
                  {#codec: codec, #schemaType: schemaType},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Block>);

  @override
  _i5.Future<dynamic> get(_i12.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#get, [cid]),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<(dynamic, String?)> resolveLink(_i12.CID? root, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#resolveLink, [root, path]),
            returnValue: _i5.Future<(dynamic, String?)>.value((null, null)),
            returnValueForMissingStub: _i5.Future<(dynamic, String?)>.value((
              null,
              null,
            )),
          )
          as _i5.Future<(dynamic, String?)>);

  @override
  _i5.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i8.SelectorResult>> executeSelector(
    _i12.CID? rootCid,
    _i8.IPLDSelector? selector,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#executeSelector, [rootCid, selector]),
            returnValue: _i5.Future<List<_i8.SelectorResult>>.value(
              <_i8.SelectorResult>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i8.SelectorResult>>.value(
                  <_i8.SelectorResult>[],
                ),
          )
          as _i5.Future<List<_i8.SelectorResult>>);

  @override
  _i5.Future<dynamic> resolvePath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePath, [path]),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.IPLDMetadata> getMetadata(_i12.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, [cid]),
            returnValue: _i5.Future<_i3.IPLDMetadata>.value(
              _FakeIPLDMetadata_1(this, Invocation.method(#getMetadata, [cid])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.IPLDMetadata>.value(
              _FakeIPLDMetadata_1(this, Invocation.method(#getMetadata, [cid])),
            ),
          )
          as _i5.Future<_i3.IPLDMetadata>);

  @override
  _i5.Future<(dynamic, _i3.IPLDMetadata)> resolveWithMetadata(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#resolveWithMetadata, [path]),
            returnValue: _i5.Future<(dynamic, _i3.IPLDMetadata)>.value((
              null,
              _FakeIPLDMetadata_1(
                this,
                Invocation.method(#resolveWithMetadata, [path]),
              ),
            )),
            returnValueForMissingStub:
                _i5.Future<(dynamic, _i3.IPLDMetadata)>.value((
                  null,
                  _FakeIPLDMetadata_1(
                    this,
                    Invocation.method(#resolveWithMetadata, [path]),
                  ),
                )),
          )
          as _i5.Future<(dynamic, _i3.IPLDMetadata)>);
}
