// Mocks generated by Mockito 5.4.6 from annotations
// in dart_ipfs/test/protocols/bitswap/bitswap_handler_coverage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i11;

import 'package:dart_ipfs/src/core/config/ipfs_config.dart' as _i5;
import 'package:dart_ipfs/src/core/data_structures/block.dart' as _i14;
import 'package:dart_ipfs/src/core/interfaces/i_block_store.dart' as _i13;
import 'package:dart_ipfs/src/proto/generated/core/blockstore.pb.dart' as _i4;
import 'package:dart_ipfs/src/protocols/bitswap/message.dart' as _i12;
import 'package:dart_ipfs/src/protocols/dht/routing_table.dart' as _i3;
import 'package:dart_ipfs/src/transport/router_events.dart' as _i10;
import 'package:dart_ipfs/src/transport/router_impl_io.dart' as _i7;
import 'package:dart_ipfs/src/utils/keystore.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:p2plib/p2plib.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePeerId_0 extends _i1.SmartFake implements _i2.PeerId {
  _FakePeerId_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouterL2_1 extends _i1.SmartFake implements _i2.RouterL2 {
  _FakeRouterL2_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutingTable_2 extends _i1.SmartFake implements _i3.RoutingTable {
  _FakeRoutingTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFullAddress_3 extends _i1.SmartFake implements _i2.FullAddress {
  _FakeFullAddress_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetBlockResponse_4 extends _i1.SmartFake
    implements _i4.GetBlockResponse {
  _FakeGetBlockResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddBlockResponse_5 extends _i1.SmartFake
    implements _i4.AddBlockResponse {
  _FakeAddBlockResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveBlockResponse_6 extends _i1.SmartFake
    implements _i4.RemoveBlockResponse {
  _FakeRemoveBlockResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetworkConfig_7 extends _i1.SmartFake implements _i5.NetworkConfig {
  _FakeNetworkConfig_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDHTConfig_8 extends _i1.SmartFake implements _i5.DHTConfig {
  _FakeDHTConfig_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStorageConfig_9 extends _i1.SmartFake implements _i5.StorageConfig {
  _FakeStorageConfig_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecurityConfig_10 extends _i1.SmartFake
    implements _i5.SecurityConfig {
  _FakeSecurityConfig_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_11 extends _i1.SmartFake implements Duration {
  _FakeDuration_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMetricsConfig_12 extends _i1.SmartFake implements _i5.MetricsConfig {
  _FakeMetricsConfig_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeystore_13 extends _i1.SmartFake implements _i6.Keystore {
  _FakeKeystore_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [P2plibRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockP2plibRouter extends _i1.Mock implements _i7.P2plibRouter {
  MockP2plibRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  List<String> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get listeningAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#listeningAddresses),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i2.PeerId get peerId =>
      (super.noSuchMethod(
            Invocation.getter(#peerId),
            returnValue: _FakePeerId_0(this, Invocation.getter(#peerId)),
          )
          as _i2.PeerId);

  @override
  Map<_i2.PeerId, _i2.Route> get routes =>
      (super.noSuchMethod(
            Invocation.getter(#routes),
            returnValue: <_i2.PeerId, _i2.Route>{},
          )
          as Map<_i2.PeerId, _i2.Route>);

  @override
  _i2.RouterL2 get routerL0 =>
      (super.noSuchMethod(
            Invocation.getter(#routerL0),
            returnValue: _FakeRouterL2_1(this, Invocation.getter(#routerL0)),
          )
          as _i2.RouterL2);

  @override
  _i9.Stream<_i10.ConnectionEvent> get connectionEvents =>
      (super.noSuchMethod(
            Invocation.getter(#connectionEvents),
            returnValue: _i9.Stream<_i10.ConnectionEvent>.empty(),
          )
          as _i9.Stream<_i10.ConnectionEvent>);

  @override
  _i9.Stream<_i10.MessageEvent> get messageEvents =>
      (super.noSuchMethod(
            Invocation.getter(#messageEvents),
            returnValue: _i9.Stream<_i10.MessageEvent>.empty(),
          )
          as _i9.Stream<_i10.MessageEvent>);

  @override
  _i9.Stream<_i10.DHTEvent> get dhtEvents =>
      (super.noSuchMethod(
            Invocation.getter(#dhtEvents),
            returnValue: _i9.Stream<_i10.DHTEvent>.empty(),
          )
          as _i9.Stream<_i10.DHTEvent>);

  @override
  _i9.Stream<_i10.PubSubEvent> get pubSubEvents =>
      (super.noSuchMethod(
            Invocation.getter(#pubSubEvents),
            returnValue: _i9.Stream<_i10.PubSubEvent>.empty(),
          )
          as _i9.Stream<_i10.PubSubEvent>);

  @override
  _i9.Stream<_i10.StreamEvent> get streamEvents =>
      (super.noSuchMethod(
            Invocation.getter(#streamEvents),
            returnValue: _i9.Stream<_i10.StreamEvent>.empty(),
          )
          as _i9.Stream<_i10.StreamEvent>);

  @override
  _i9.Stream<_i10.ErrorEvent> get errorEvents =>
      (super.noSuchMethod(
            Invocation.getter(#errorEvents),
            returnValue: _i9.Stream<_i10.ErrorEvent>.empty(),
          )
          as _i9.Stream<_i10.ErrorEvent>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i2.PeerId get localPeerId =>
      (super.noSuchMethod(
            Invocation.getter(#localPeerId),
            returnValue: _FakePeerId_0(this, Invocation.getter(#localPeerId)),
          )
          as _i2.PeerId);

  @override
  List<String> resolvePeer(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeer, [peerIdStr]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> connect(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [multiaddress]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> disconnect(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [multiaddress]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  List<String> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i9.Future<void> sendMessage(
    String? peerIdStr,
    _i11.Uint8List? message, {
    String? protocolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [peerIdStr, message],
              {#protocolId: protocolId},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<String> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i9.Stream<String>.empty(),
          )
          as _i9.Stream<String>);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void onMessage(void Function(_i12.Message)? handler) => super.noSuchMethod(
    Invocation.method(#onMessage, [handler]),
    returnValueForMissingStub: null,
  );

  @override
  void registerProtocolHandler(
    String? protocolId,
    void Function(_i10.NetworkPacket)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#registerProtocolHandler, [protocolId, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void removeMessageHandler(String? protocolId) => super.noSuchMethod(
    Invocation.method(#removeMessageHandler, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> sendDatagram({
    required List<String>? addresses,
    required _i11.Uint8List? datagram,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendDatagram, [], {
              #addresses: addresses,
              #datagram: datagram,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i3.RoutingTable getRoutingTable() =>
      (super.noSuchMethod(
            Invocation.method(#getRoutingTable, []),
            returnValue: _FakeRoutingTable_2(
              this,
              Invocation.method(#getRoutingTable, []),
            ),
          )
          as _i3.RoutingTable);

  @override
  _i9.Future<void> emitEvent(String? topic, _i11.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#emitEvent, [topic, data]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void onEvent(String? topic, void Function(_i10.NetworkMessage)? handler) =>
      super.noSuchMethod(
        Invocation.method(#onEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void offEvent(String? topic, void Function(_i10.NetworkMessage)? handler) =>
      super.noSuchMethod(
        Invocation.method(#offEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i2.FullAddress parseMultiaddr(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#parseMultiaddr, [multiaddr]),
            returnValue: _FakeFullAddress_3(
              this,
              Invocation.method(#parseMultiaddr, [multiaddr]),
            ),
          )
          as _i2.FullAddress);

  @override
  bool isConnectedPeer(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#isConnectedPeer, [peerIdStr]),
            returnValue: false,
          )
          as bool);

  @override
  void registerProtocol(String? protocolId) => super.noSuchMethod(
    Invocation.method(#registerProtocol, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<_i11.Uint8List> sendRequest(
    String? peerId,
    String? protocolId,
    _i11.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i9.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
          )
          as _i9.Future<_i11.Uint8List>);

  @override
  _i9.Future<void> broadcastMessage(
    String? protocolId,
    _i11.Uint8List? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastMessage, [protocolId, message]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [IBlockStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBlockStore extends _i1.Mock implements _i13.IBlockStore {
  MockIBlockStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.GetBlockResponse> getBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#getBlock, [cid]),
            returnValue: _i9.Future<_i4.GetBlockResponse>.value(
              _FakeGetBlockResponse_4(
                this,
                Invocation.method(#getBlock, [cid]),
              ),
            ),
          )
          as _i9.Future<_i4.GetBlockResponse>);

  @override
  _i9.Future<_i4.AddBlockResponse> putBlock(_i14.Block? block) =>
      (super.noSuchMethod(
            Invocation.method(#putBlock, [block]),
            returnValue: _i9.Future<_i4.AddBlockResponse>.value(
              _FakeAddBlockResponse_5(
                this,
                Invocation.method(#putBlock, [block]),
              ),
            ),
          )
          as _i9.Future<_i4.AddBlockResponse>);

  @override
  _i9.Future<_i4.RemoveBlockResponse> removeBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#removeBlock, [cid]),
            returnValue: _i9.Future<_i4.RemoveBlockResponse>.value(
              _FakeRemoveBlockResponse_6(
                this,
                Invocation.method(#removeBlock, [cid]),
              ),
            ),
          )
          as _i9.Future<_i4.RemoveBlockResponse>);

  @override
  _i9.Future<List<_i14.Block>> getAllBlocks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBlocks, []),
            returnValue: _i9.Future<List<_i14.Block>>.value(<_i14.Block>[]),
          )
          as _i9.Future<List<_i14.Block>>);

  @override
  _i9.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<bool> hasBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#hasBlock, [cid]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}

/// A class which mocks [IPFSConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPFSConfig extends _i1.Mock implements _i5.IPFSConfig {
  MockIPFSConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.NetworkConfig get network =>
      (super.noSuchMethod(
            Invocation.getter(#network),
            returnValue: _FakeNetworkConfig_7(
              this,
              Invocation.getter(#network),
            ),
          )
          as _i5.NetworkConfig);

  @override
  _i5.DHTConfig get dht =>
      (super.noSuchMethod(
            Invocation.getter(#dht),
            returnValue: _FakeDHTConfig_8(this, Invocation.getter(#dht)),
          )
          as _i5.DHTConfig);

  @override
  _i5.StorageConfig get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeStorageConfig_9(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i5.StorageConfig);

  @override
  _i5.SecurityConfig get security =>
      (super.noSuchMethod(
            Invocation.getter(#security),
            returnValue: _FakeSecurityConfig_10(
              this,
              Invocation.getter(#security),
            ),
          )
          as _i5.SecurityConfig);

  @override
  bool get debug =>
      (super.noSuchMethod(Invocation.getter(#debug), returnValue: false)
          as bool);

  @override
  bool get verboseLogging =>
      (super.noSuchMethod(
            Invocation.getter(#verboseLogging),
            returnValue: false,
          )
          as bool);

  @override
  bool get enablePubSub =>
      (super.noSuchMethod(Invocation.getter(#enablePubSub), returnValue: false)
          as bool);

  @override
  bool get enableDHT =>
      (super.noSuchMethod(Invocation.getter(#enableDHT), returnValue: false)
          as bool);

  @override
  bool get enableCircuitRelay =>
      (super.noSuchMethod(
            Invocation.getter(#enableCircuitRelay),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableContentRouting =>
      (super.noSuchMethod(
            Invocation.getter(#enableContentRouting),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableDNSLinkResolution =>
      (super.noSuchMethod(
            Invocation.getter(#enableDNSLinkResolution),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableIPLD =>
      (super.noSuchMethod(Invocation.getter(#enableIPLD), returnValue: false)
          as bool);

  @override
  bool get enableGraphsync =>
      (super.noSuchMethod(
            Invocation.getter(#enableGraphsync),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableMetrics =>
      (super.noSuchMethod(Invocation.getter(#enableMetrics), returnValue: false)
          as bool);

  @override
  bool get enableLogging =>
      (super.noSuchMethod(Invocation.getter(#enableLogging), returnValue: false)
          as bool);

  @override
  String get logLevel =>
      (super.noSuchMethod(
            Invocation.getter(#logLevel),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#logLevel),
            ),
          )
          as String);

  @override
  bool get enableQuotaManagement =>
      (super.noSuchMethod(
            Invocation.getter(#enableQuotaManagement),
            returnValue: false,
          )
          as bool);

  @override
  int get defaultBandwidthQuota =>
      (super.noSuchMethod(
            Invocation.getter(#defaultBandwidthQuota),
            returnValue: 0,
          )
          as int);

  @override
  String get datastorePath =>
      (super.noSuchMethod(
            Invocation.getter(#datastorePath),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#datastorePath),
            ),
          )
          as String);

  @override
  String get keystorePath =>
      (super.noSuchMethod(
            Invocation.getter(#keystorePath),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#keystorePath),
            ),
          )
          as String);

  @override
  String get blockStorePath =>
      (super.noSuchMethod(
            Invocation.getter(#blockStorePath),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#blockStorePath),
            ),
          )
          as String);

  @override
  bool get enableLibp2pBridge =>
      (super.noSuchMethod(
            Invocation.getter(#enableLibp2pBridge),
            returnValue: false,
          )
          as bool);

  @override
  String get libp2pListenAddress =>
      (super.noSuchMethod(
            Invocation.getter(#libp2pListenAddress),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#libp2pListenAddress),
            ),
          )
          as String);

  @override
  String get nodeId =>
      (super.noSuchMethod(
            Invocation.getter(#nodeId),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#nodeId),
            ),
          )
          as String);

  @override
  Duration get garbageCollectionInterval =>
      (super.noSuchMethod(
            Invocation.getter(#garbageCollectionInterval),
            returnValue: _FakeDuration_11(
              this,
              Invocation.getter(#garbageCollectionInterval),
            ),
          )
          as Duration);

  @override
  bool get garbageCollectionEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#garbageCollectionEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i5.MetricsConfig get metrics =>
      (super.noSuchMethod(
            Invocation.getter(#metrics),
            returnValue: _FakeMetricsConfig_12(
              this,
              Invocation.getter(#metrics),
            ),
          )
          as _i5.MetricsConfig);

  @override
  String get dataPath =>
      (super.noSuchMethod(
            Invocation.getter(#dataPath),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#dataPath),
            ),
          )
          as String);

  @override
  _i6.Keystore get keystore =>
      (super.noSuchMethod(
            Invocation.getter(#keystore),
            returnValue: _FakeKeystore_13(this, Invocation.getter(#keystore)),
          )
          as _i6.Keystore);

  @override
  bool get offline =>
      (super.noSuchMethod(Invocation.getter(#offline), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> get customConfig =>
      (super.noSuchMethod(
            Invocation.getter(#customConfig),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
