// Mocks generated by Mockito from annotations
// in dart_ipfs/test/core/ipfs_node/bootstrap_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i7;
import 'dart:typed_data' as _i10;

import 'package:dart_ipfs/src/core/config/ipfs_config.dart' as _i5;
import 'package:dart_ipfs/src/core/ipfs_node/ipfs_node.dart' as _i2;
import 'package:dart_ipfs/src/core/ipfs_node/network_handler_io.dart' as _i6;
import 'package:dart_ipfs/src/proto/generated/dht/ipfs_node_network_events.pb.dart'
    as _i8;
import 'package:dart_ipfs/src/transport/circuit_relay_client.dart' as _i4;
import 'package:dart_ipfs/src/transport/router_interface.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIPFSNode_0 extends _i1.SmartFake implements _i2.IPFSNode {
  _FakeIPFSNode_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouterInterface_1 extends _i1.SmartFake
    implements _i3.RouterInterface {
  _FakeRouterInterface_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCircuitRelayClient_2 extends _i1.SmartFake
    implements _i4.CircuitRelayClient {
  _FakeCircuitRelayClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPFSConfig_3 extends _i1.SmartFake implements _i5.IPFSConfig {
  _FakeIPFSConfig_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkHandler extends _i1.Mock implements _i6.NetworkHandler {
  @override
  _i2.IPFSNode get ipfsNode =>
      (super.noSuchMethod(
            Invocation.getter(#ipfsNode),
            returnValue: _FakeIPFSNode_0(this, Invocation.getter(#ipfsNode)),
            returnValueForMissingStub: _FakeIPFSNode_0(
              this,
              Invocation.getter(#ipfsNode),
            ),
          )
          as _i2.IPFSNode);

  @override
  _i3.RouterInterface get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
            returnValueForMissingStub: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i3.RouterInterface);

  @override
  _i7.Stream<_i8.NetworkEvent> get networkEvents =>
      (super.noSuchMethod(
            Invocation.getter(#networkEvents),
            returnValue: _i7.Stream<_i8.NetworkEvent>.empty(),
            returnValueForMissingStub: _i7.Stream<_i8.NetworkEvent>.empty(),
          )
          as _i7.Stream<_i8.NetworkEvent>);

  @override
  _i4.CircuitRelayClient get circuitRelayClient =>
      (super.noSuchMethod(
            Invocation.getter(#circuitRelayClient),
            returnValue: _FakeCircuitRelayClient_2(
              this,
              Invocation.getter(#circuitRelayClient),
            ),
            returnValueForMissingStub: _FakeCircuitRelayClient_2(
              this,
              Invocation.getter(#circuitRelayClient),
            ),
          )
          as _i4.CircuitRelayClient);

  @override
  _i5.IPFSConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeIPFSConfig_3(this, Invocation.getter(#config)),
            returnValueForMissingStub: _FakeIPFSConfig_3(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i5.IPFSConfig);

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  _i7.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> connectToPeer(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connectToPeer, [multiaddress]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> disconnectFromPeer(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromPeer, [multiaddress]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<String>> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i7.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<void> sendMessage(String? peerId, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [peerId, message]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Stream<String> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i7.Stream<String>.empty(),
            returnValueForMissingStub: _i7.Stream<String>.empty(),
          )
          as _i7.Stream<String>);

  @override
  void setIpfsNode(_i2.IPFSNode? node) => super.noSuchMethod(
    Invocation.method(#setIpfsNode, [node]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i10.Uint8List?> sendRequest(
    String? peerId,
    String? protocolId,
    _i10.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i7.Future<_i10.Uint8List?>.value(),
            returnValueForMissingStub: _i7.Future<_i10.Uint8List?>.value(),
          )
          as _i7.Future<_i10.Uint8List?>);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> canConnectDirectly(String? peerAddress) =>
      (super.noSuchMethod(
            Invocation.method(#canConnectDirectly, [peerAddress]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> testDialback() =>
      (super.noSuchMethod(
            Invocation.method(#testDialback, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}
