// Mocks generated by Mockito 5.4.6 from annotations
// in dart_ipfs/test/core/ipfs_node/ipfs_node_network_events_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:dart_ipfs/src/transport/router_events.dart' as _i5;
import 'package:dart_ipfs/src/transport/router_interface.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RouterInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterInterface extends _i1.Mock implements _i2.RouterInterface {
  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  bool get hasStarted =>
      (super.noSuchMethod(
            Invocation.getter(#hasStarted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Set<String> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  _i4.Stream<_i5.ConnectionEvent> get connectionEvents =>
      (super.noSuchMethod(
            Invocation.getter(#connectionEvents),
            returnValue: _i4.Stream<_i5.ConnectionEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i5.ConnectionEvent>.empty(),
          )
          as _i4.Stream<_i5.ConnectionEvent>);

  @override
  _i4.Stream<_i5.MessageEvent> get messageEvents =>
      (super.noSuchMethod(
            Invocation.getter(#messageEvents),
            returnValue: _i4.Stream<_i5.MessageEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i5.MessageEvent>.empty(),
          )
          as _i4.Stream<_i5.MessageEvent>);

  @override
  List<String> get listeningAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#listeningAddresses),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connect(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [multiaddress]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect(String? peerIdOrMultiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [peerIdOrMultiaddress]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<String> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool isConnectedPeer(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#isConnectedPeer, [peerIdStr]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> sendMessage(
    String? peerIdStr,
    _i6.Uint8List? message, {
    String? protocolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [peerIdStr, message],
              {#protocolId: protocolId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.Uint8List?> sendRequest(
    String? peerId,
    String? protocolId,
    _i6.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i4.Future<_i6.Uint8List?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.Uint8List?>.value(),
          )
          as _i4.Future<_i6.Uint8List?>);

  @override
  _i4.Stream<_i6.Uint8List> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i4.Stream<_i6.Uint8List>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.Uint8List>.empty(),
          )
          as _i4.Stream<_i6.Uint8List>);

  @override
  void registerProtocolHandler(
    String? protocolId,
    void Function(_i5.NetworkPacket)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#registerProtocolHandler, [protocolId, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void removeMessageHandler(String? protocolId) => super.noSuchMethod(
    Invocation.method(#removeMessageHandler, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  void registerProtocol(String? protocolId) => super.noSuchMethod(
    Invocation.method(#registerProtocol, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> broadcastMessage(
    String? protocolId,
    _i6.Uint8List? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastMessage, [protocolId, message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void emitEvent(String? topic, _i6.Uint8List? data) => super.noSuchMethod(
    Invocation.method(#emitEvent, [topic, data]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#onEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void offEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#offEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  Object? parseMultiaddr(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#parseMultiaddr, [multiaddr]),
            returnValueForMissingStub: null,
          )
          as Object?);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);
}
