// Mocks generated by Mockito from annotations
// in dart_ipfs/test/core/ipfs_node/network_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i12;
import 'dart:typed_data' as _i15;

import 'package:dart_ipfs/src/core/cid.dart' as _i19;
import 'package:dart_ipfs/src/core/config/ipfs_config.dart' as _i5;
import 'package:dart_ipfs/src/core/data_structures/block.dart' as _i22;
import 'package:dart_ipfs/src/core/data_structures/peer.dart' as _i24;
import 'package:dart_ipfs/src/core/ipfs_node/content_routing_handler.dart'
    as _i20;
import 'package:dart_ipfs/src/core/ipfs_node/datastore_handler.dart' as _i21;
import 'package:dart_ipfs/src/core/ipfs_node/ipfs_node.dart' as _i2;
import 'package:dart_ipfs/src/core/ipfs_node/network_handler.dart' as _i11;
import 'package:dart_ipfs/src/core/storage/datastore.dart' as _i7;
import 'package:dart_ipfs/src/core/types/peer_id.dart' as _i9;
import 'package:dart_ipfs/src/proto/generated/core/peer.pb.dart' as _i10;
import 'package:dart_ipfs/src/proto/generated/dht/common_red_black_tree.pb.dart'
    as _i18;
import 'package:dart_ipfs/src/proto/generated/dht/ipfs_node_network_events.pb.dart'
    as _i13;
import 'package:dart_ipfs/src/protocols/bitswap/bitswap_handler.dart' as _i23;
import 'package:dart_ipfs/src/protocols/dht/dht_client.dart' as _i6;
import 'package:dart_ipfs/src/protocols/dht/dht_handler.dart' as _i17;
import 'package:dart_ipfs/src/protocols/dht/interface_dht_handler.dart' as _i8;
import 'package:dart_ipfs/src/transport/circuit_relay_client.dart' as _i4;
import 'package:dart_ipfs/src/transport/router_events.dart' as _i16;
import 'package:dart_ipfs/src/transport/router_interface.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIPFSNode_0 extends _i1.SmartFake implements _i2.IPFSNode {
  _FakeIPFSNode_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouterInterface_1 extends _i1.SmartFake
    implements _i3.RouterInterface {
  _FakeRouterInterface_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCircuitRelayClient_2 extends _i1.SmartFake
    implements _i4.CircuitRelayClient {
  _FakeCircuitRelayClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPFSConfig_3 extends _i1.SmartFake implements _i5.IPFSConfig {
  _FakeIPFSConfig_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDHTClient_4 extends _i1.SmartFake implements _i6.DHTClient {
  _FakeDHTClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatastore_5 extends _i1.SmartFake implements _i7.Datastore {
  _FakeDatastore_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValue_6 extends _i1.SmartFake implements _i8.Value {
  _FakeValue_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeerId_7 extends _i1.SmartFake implements _i9.PeerId {
  _FakePeerId_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeerProto_8 extends _i1.SmartFake implements _i10.PeerProto {
  _FakePeerProto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkHandler extends _i1.Mock implements _i11.NetworkHandler {
  @override
  _i2.IPFSNode get ipfsNode =>
      (super.noSuchMethod(
            Invocation.getter(#ipfsNode),
            returnValue: _FakeIPFSNode_0(this, Invocation.getter(#ipfsNode)),
            returnValueForMissingStub: _FakeIPFSNode_0(
              this,
              Invocation.getter(#ipfsNode),
            ),
          )
          as _i2.IPFSNode);

  @override
  _i3.RouterInterface get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
            returnValueForMissingStub: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i3.RouterInterface);

  @override
  _i12.Stream<_i13.NetworkEvent> get networkEvents =>
      (super.noSuchMethod(
            Invocation.getter(#networkEvents),
            returnValue: _i12.Stream<_i13.NetworkEvent>.empty(),
            returnValueForMissingStub: _i12.Stream<_i13.NetworkEvent>.empty(),
          )
          as _i12.Stream<_i13.NetworkEvent>);

  @override
  _i4.CircuitRelayClient get circuitRelayClient =>
      (super.noSuchMethod(
            Invocation.getter(#circuitRelayClient),
            returnValue: _FakeCircuitRelayClient_2(
              this,
              Invocation.getter(#circuitRelayClient),
            ),
            returnValueForMissingStub: _FakeCircuitRelayClient_2(
              this,
              Invocation.getter(#circuitRelayClient),
            ),
          )
          as _i4.CircuitRelayClient);

  @override
  _i5.IPFSConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeIPFSConfig_3(this, Invocation.getter(#config)),
            returnValueForMissingStub: _FakeIPFSConfig_3(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i5.IPFSConfig);

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> connectToPeer(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connectToPeer, [multiaddress]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> disconnectFromPeer(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromPeer, [multiaddress]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<String>> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<void> sendMessage(String? peerId, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [peerId, message]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<String> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i12.Stream<String>.empty(),
            returnValueForMissingStub: _i12.Stream<String>.empty(),
          )
          as _i12.Stream<String>);

  @override
  void setIpfsNode(_i2.IPFSNode? node) => super.noSuchMethod(
    Invocation.method(#setIpfsNode, [node]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i15.Uint8List?> sendRequest(
    String? peerId,
    String? protocolId,
    _i15.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i12.Future<_i15.Uint8List?>.value(),
            returnValueForMissingStub: _i12.Future<_i15.Uint8List?>.value(),
          )
          as _i12.Future<_i15.Uint8List?>);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> canConnectDirectly(String? peerAddress) =>
      (super.noSuchMethod(
            Invocation.method(#canConnectDirectly, [peerAddress]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> testDialback() =>
      (super.noSuchMethod(
            Invocation.method(#testDialback, []),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}

/// A class which mocks [RouterInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterInterface extends _i1.Mock implements _i3.RouterInterface {
  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  bool get hasStarted =>
      (super.noSuchMethod(
            Invocation.getter(#hasStarted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Set<String> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  _i12.Stream<_i16.ConnectionEvent> get connectionEvents =>
      (super.noSuchMethod(
            Invocation.getter(#connectionEvents),
            returnValue: _i12.Stream<_i16.ConnectionEvent>.empty(),
            returnValueForMissingStub:
                _i12.Stream<_i16.ConnectionEvent>.empty(),
          )
          as _i12.Stream<_i16.ConnectionEvent>);

  @override
  _i12.Stream<_i16.MessageEvent> get messageEvents =>
      (super.noSuchMethod(
            Invocation.getter(#messageEvents),
            returnValue: _i12.Stream<_i16.MessageEvent>.empty(),
            returnValueForMissingStub: _i12.Stream<_i16.MessageEvent>.empty(),
          )
          as _i12.Stream<_i16.MessageEvent>);

  @override
  List<String> get listeningAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#listeningAddresses),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  Set<String> get supportedProtocols =>
      (super.noSuchMethod(
            Invocation.getter(#supportedProtocols),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> connect(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [multiaddress]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> disconnect(String? peerIdOrMultiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [peerIdOrMultiaddress]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  List<String> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool isConnectedPeer(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#isConnectedPeer, [peerIdStr]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<void> sendMessage(
    String? peerIdStr,
    _i15.Uint8List? message, {
    String? protocolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [peerIdStr, message],
              {#protocolId: protocolId},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i15.Uint8List?> sendRequest(
    String? peerId,
    String? protocolId,
    _i15.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i12.Future<_i15.Uint8List?>.value(),
            returnValueForMissingStub: _i12.Future<_i15.Uint8List?>.value(),
          )
          as _i12.Future<_i15.Uint8List?>);

  @override
  _i12.Stream<_i15.Uint8List> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i12.Stream<_i15.Uint8List>.empty(),
            returnValueForMissingStub: _i12.Stream<_i15.Uint8List>.empty(),
          )
          as _i12.Stream<_i15.Uint8List>);

  @override
  void registerProtocolHandler(
    String? protocolId,
    void Function(_i16.NetworkPacket)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#registerProtocolHandler, [protocolId, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void removeMessageHandler(String? protocolId) => super.noSuchMethod(
    Invocation.method(#removeMessageHandler, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterProtocolHandler(String? protocolId) => super.noSuchMethod(
    Invocation.method(#unregisterProtocolHandler, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i15.Uint8List> sendMessageWithResponse(
    String? peerId,
    _i15.Uint8List? message, {
    String? protocolId,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageWithResponse,
              [peerId, message],
              {#protocolId: protocolId, #timeout: timeout},
            ),
            returnValue: _i12.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
            returnValueForMissingStub: _i12.Future<_i15.Uint8List>.value(
              _i15.Uint8List(0),
            ),
          )
          as _i12.Future<_i15.Uint8List>);

  @override
  void registerProtocol(String? protocolId) => super.noSuchMethod(
    Invocation.method(#registerProtocol, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> broadcastMessage(
    String? protocolId,
    _i15.Uint8List? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastMessage, [protocolId, message]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void emitEvent(String? topic, _i15.Uint8List? data) => super.noSuchMethod(
    Invocation.method(#emitEvent, [topic, data]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#onEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void offEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#offEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  Object? parseMultiaddr(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#parseMultiaddr, [multiaddr]),
            returnValueForMissingStub: null,
          )
          as Object?);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  void registerRelayedConnection(String? targetPeerId, String? relayAddr) =>
      super.noSuchMethod(
        Invocation.method(#registerRelayedConnection, [
          targetPeerId,
          relayAddr,
        ]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DHTHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockDHTHandler extends _i1.Mock implements _i17.DHTHandler {
  @override
  _i6.DHTClient get dhtClient =>
      (super.noSuchMethod(
            Invocation.getter(#dhtClient),
            returnValue: _FakeDHTClient_4(this, Invocation.getter(#dhtClient)),
            returnValueForMissingStub: _FakeDHTClient_4(
              this,
              Invocation.getter(#dhtClient),
            ),
          )
          as _i6.DHTClient);

  @override
  _i3.RouterInterface get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
            returnValueForMissingStub: _FakeRouterInterface_1(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i3.RouterInterface);

  @override
  _i7.Datastore get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeDatastore_5(this, Invocation.getter(#storage)),
            returnValueForMissingStub: _FakeDatastore_5(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i7.Datastore);

  @override
  set dhtClient(_i6.DHTClient? value) => super.noSuchMethod(
    Invocation.setter(#dhtClient, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i18.V_PeerInfo>> findProviders(_i19.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i12.Future<List<_i18.V_PeerInfo>>.value(
              <_i18.V_PeerInfo>[],
            ),
            returnValueForMissingStub: _i12.Future<List<_i18.V_PeerInfo>>.value(
              <_i18.V_PeerInfo>[],
            ),
          )
          as _i12.Future<List<_i18.V_PeerInfo>>);

  @override
  _i12.Future<void> putValue(_i8.Key? key, _i8.Value? value) =>
      (super.noSuchMethod(
            Invocation.method(#putValue, [key, value]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i8.Value> getValue(_i8.Key? key) =>
      (super.noSuchMethod(
            Invocation.method(#getValue, [key]),
            returnValue: _i12.Future<_i8.Value>.value(
              _FakeValue_6(this, Invocation.method(#getValue, [key])),
            ),
            returnValueForMissingStub: _i12.Future<_i8.Value>.value(
              _FakeValue_6(this, Invocation.method(#getValue, [key])),
            ),
          )
          as _i12.Future<_i8.Value>);

  @override
  _i12.Future<String> resolveIPNS(String? ipnsName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveIPNS, [ipnsName]),
            returnValue: _i12.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [ipnsName]),
              ),
            ),
            returnValueForMissingStub: _i12.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [ipnsName]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> publishIPNS(String? cid, {required String? keyName}) =>
      (super.noSuchMethod(
            Invocation.method(#publishIPNS, [cid], {#keyName: keyName}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  bool isValidCID(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#isValidCID, [cid]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isValidPeerID(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#isValidPeerID, [peerId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isValidProviderRecord(
    _i9.PeerId? provider,
    String? cid,
    DateTime? ttl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isValidProviderRecord, [provider, cid, ttl]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String? extractCIDFromResponse(String? responseBody) =>
      (super.noSuchMethod(
            Invocation.method(#extractCIDFromResponse, [responseBody]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i12.Future<List<_i18.V_PeerInfo>> findPeer(_i9.PeerId? id) =>
      (super.noSuchMethod(
            Invocation.method(#findPeer, [id]),
            returnValue: _i12.Future<List<_i18.V_PeerInfo>>.value(
              <_i18.V_PeerInfo>[],
            ),
            returnValueForMissingStub: _i12.Future<List<_i18.V_PeerInfo>>.value(
              <_i18.V_PeerInfo>[],
            ),
          )
          as _i12.Future<List<_i18.V_PeerInfo>>);

  @override
  _i12.Future<void> provide(_i19.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#provide, [cid]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> provideAll(List<_i19.CID>? cids) =>
      (super.noSuchMethod(
            Invocation.method(#provideAll, [cids]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> handleRoutingTableUpdate(_i18.V_PeerInfo? peer) =>
      (super.noSuchMethod(
            Invocation.method(#handleRoutingTableUpdate, [peer]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> handleProvideRequest(_i19.CID? cid, _i9.PeerId? provider) =>
      (super.noSuchMethod(
            Invocation.method(#handleProvideRequest, [cid, provider]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  List<_i9.PeerId> getLocalProvidersForCid(String? cidStr) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalProvidersForCid, [cidStr]),
            returnValue: <_i9.PeerId>[],
            returnValueForMissingStub: <_i9.PeerId>[],
          )
          as List<_i9.PeerId>);

  @override
  _i12.Future<String?> resolveDNSLink(String? domainName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDNSLink, [domainName]),
            returnValue: _i12.Future<String?>.value(),
            returnValueForMissingStub: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);
}

/// A class which mocks [ContentRoutingHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentRoutingHandler extends _i1.Mock
    implements _i20.ContentRoutingHandler {
  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<String>> findProviders(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<String?> resolveDNSLink(String? domainName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDNSLink, [domainName]),
            returnValue: _i12.Future<String?>.value(),
            returnValueForMissingStub: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);
}

/// A class which mocks [DatastoreHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatastoreHandler extends _i1.Mock implements _i21.DatastoreHandler {
  @override
  _i7.Datastore get datastore =>
      (super.noSuchMethod(
            Invocation.getter(#datastore),
            returnValue: _FakeDatastore_5(this, Invocation.getter(#datastore)),
            returnValueForMissingStub: _FakeDatastore_5(
              this,
              Invocation.getter(#datastore),
            ),
          )
          as _i7.Datastore);

  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> putBlock(_i22.Block? block) =>
      (super.noSuchMethod(
            Invocation.method(#putBlock, [block]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i22.Block?> getBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#getBlock, [cid]),
            returnValue: _i12.Future<_i22.Block?>.value(),
            returnValueForMissingStub: _i12.Future<_i22.Block?>.value(),
          )
          as _i12.Future<_i22.Block?>);

  @override
  _i12.Future<bool> hasBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#hasBlock, [cid]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<Set<String>> loadPinnedCIDs() =>
      (super.noSuchMethod(
            Invocation.method(#loadPinnedCIDs, []),
            returnValue: _i12.Future<Set<String>>.value(<String>{}),
            returnValueForMissingStub: _i12.Future<Set<String>>.value(
              <String>{},
            ),
          )
          as _i12.Future<Set<String>>);

  @override
  _i12.Future<void> persistPinnedCIDs(Set<String>? pinnedCIDs) =>
      (super.noSuchMethod(
            Invocation.method(#persistPinnedCIDs, [pinnedCIDs]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> importCAR(_i15.Uint8List? carFile) =>
      (super.noSuchMethod(
            Invocation.method(#importCAR, [carFile]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i15.Uint8List> exportCAR(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#exportCAR, [cid]),
            returnValue: _i12.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
            returnValueForMissingStub: _i12.Future<_i15.Uint8List>.value(
              _i15.Uint8List(0),
            ),
          )
          as _i12.Future<_i15.Uint8List>);

  @override
  _i12.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);
}

/// A class which mocks [BitswapHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockBitswapHandler extends _i1.Mock implements _i23.BitswapHandler {
  @override
  int get bandwidthSent =>
      (super.noSuchMethod(
            Invocation.getter(#bandwidthSent),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get bandwidthReceived =>
      (super.noSuchMethod(
            Invocation.getter(#bandwidthReceived),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> handleBlocks(List<_i22.Block>? blocks) =>
      (super.noSuchMethod(
            Invocation.method(#handleBlocks, [blocks]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i22.Block>> want(
    List<String>? cids, {
    int? priority = 1,
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #want,
              [cids],
              {#priority: priority, #timeout: timeout},
            ),
            returnValue: _i12.Future<List<_i22.Block>>.value(<_i22.Block>[]),
            returnValueForMissingStub: _i12.Future<List<_i22.Block>>.value(
              <_i22.Block>[],
            ),
          )
          as _i12.Future<List<_i22.Block>>);

  @override
  _i12.Future<void> handleWantRequest(String? cidStr) =>
      (super.noSuchMethod(
            Invocation.method(#handleWantRequest, [cidStr]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i22.Block?> wantBlock(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#wantBlock, [cid]),
            returnValue: _i12.Future<_i22.Block?>.value(),
            returnValueForMissingStub: _i12.Future<_i22.Block?>.value(),
          )
          as _i12.Future<_i22.Block?>);

  @override
  _i12.Future<_i22.Block?> getBlock(
    String? cidStr, {
    bool? useHttpFallback = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBlock,
              [cidStr],
              {#useHttpFallback: useHttpFallback},
            ),
            returnValue: _i12.Future<_i22.Block?>.value(),
            returnValueForMissingStub: _i12.Future<_i22.Block?>.value(),
          )
          as _i12.Future<_i22.Block?>);

  @override
  _i12.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);
}

/// A class which mocks [Peer].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeer extends _i1.Mock implements _i24.Peer {
  @override
  _i9.PeerId get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _FakePeerId_7(this, Invocation.getter(#id)),
            returnValueForMissingStub: _FakePeerId_7(
              this,
              Invocation.getter(#id),
            ),
          )
          as _i9.PeerId);

  @override
  List<_i24.FullAddress> get addresses =>
      (super.noSuchMethod(
            Invocation.getter(#addresses),
            returnValue: <_i24.FullAddress>[],
            returnValueForMissingStub: <_i24.FullAddress>[],
          )
          as List<_i24.FullAddress>);

  @override
  int get latency =>
      (super.noSuchMethod(
            Invocation.getter(#latency),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get agentVersion =>
      (super.noSuchMethod(
            Invocation.getter(#agentVersion),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#agentVersion),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#agentVersion),
            ),
          )
          as String);

  @override
  _i10.PeerProto toProto() =>
      (super.noSuchMethod(
            Invocation.method(#toProto, []),
            returnValue: _FakePeerProto_8(
              this,
              Invocation.method(#toProto, []),
            ),
            returnValueForMissingStub: _FakePeerProto_8(
              this,
              Invocation.method(#toProto, []),
            ),
          )
          as _i10.PeerProto);
}
