// Mocks generated by Mockito 5.4.6 from annotations
// in dart_ipfs/test/core/ipfs_node/network_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:typed_data' as _i14;

import 'package:dart_ipfs/src/core/cid.dart' as _i20;
import 'package:dart_ipfs/src/core/data_structures/blockstore.dart' as _i2;
import 'package:dart_ipfs/src/core/data_structures/link.dart' as _i16;
import 'package:dart_ipfs/src/core/data_structures/peer.dart' as _i17;
import 'package:dart_ipfs/src/core/ipfs_node/ipfs_node.dart' as _i7;
import 'package:dart_ipfs/src/core/ipfs_node/network_handler.dart' as _i8;
import 'package:dart_ipfs/src/core/storage/datastore.dart' as _i4;
import 'package:dart_ipfs/src/core/types/peer_id.dart' as _i9;
import 'package:dart_ipfs/src/proto/generated/dht/common_red_black_tree.pb.dart'
    as _i19;
import 'package:dart_ipfs/src/protocols/dht/dht_client.dart' as _i3;
import 'package:dart_ipfs/src/protocols/dht/dht_handler.dart' as _i18;
import 'package:dart_ipfs/src/protocols/dht/interface_dht_handler.dart' as _i6;
import 'package:dart_ipfs/src/protocols/dht/kademlia_routing_table.dart'
    as _i10;
import 'package:dart_ipfs/src/protocols/dht/kademlia_tree/kademlia_tree_node.dart'
    as _i22;
import 'package:dart_ipfs/src/protocols/dht/red_black_tree.dart' as _i21;
import 'package:dart_ipfs/src/protocols/pubsub/pubsub_message.dart' as _i15;
import 'package:dart_ipfs/src/transport/router_events.dart' as _i13;
import 'package:dart_ipfs/src/transport/router_interface.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBlockStore_0 extends _i1.SmartFake implements _i2.BlockStore {
  _FakeBlockStore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDHTClient_1 extends _i1.SmartFake implements _i3.DHTClient {
  _FakeDHTClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatastore_2 extends _i1.SmartFake implements _i4.Datastore {
  _FakeDatastore_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouterInterface_3 extends _i1.SmartFake
    implements _i5.RouterInterface {
  _FakeRouterInterface_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValue_4 extends _i1.SmartFake implements _i6.Value {
  _FakeValue_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPFSNode_5 extends _i1.SmartFake implements _i7.IPFSNode {
  _FakeIPFSNode_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetworkHandler_6 extends _i1.SmartFake
    implements _i8.NetworkHandler {
  _FakeNetworkHandler_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeerId_7 extends _i1.SmartFake implements _i9.PeerId {
  _FakePeerId_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKademliaRoutingTable_8 extends _i1.SmartFake
    implements _i10.KademliaRoutingTable {
  _FakeKademliaRoutingTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RouterInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterInterface extends _i1.Mock implements _i5.RouterInterface {
  MockRouterInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  bool get hasStarted =>
      (super.noSuchMethod(Invocation.getter(#hasStarted), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  Set<String> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  _i12.Stream<_i13.ConnectionEvent> get connectionEvents =>
      (super.noSuchMethod(
            Invocation.getter(#connectionEvents),
            returnValue: _i12.Stream<_i13.ConnectionEvent>.empty(),
          )
          as _i12.Stream<_i13.ConnectionEvent>);

  @override
  _i12.Stream<_i13.MessageEvent> get messageEvents =>
      (super.noSuchMethod(
            Invocation.getter(#messageEvents),
            returnValue: _i12.Stream<_i13.MessageEvent>.empty(),
          )
          as _i12.Stream<_i13.MessageEvent>);

  @override
  List<String> get listeningAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#listeningAddresses),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> connect(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [multiaddress]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> disconnect(String? peerIdOrMultiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [peerIdOrMultiaddress]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  List<String> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool isConnectedPeer(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#isConnectedPeer, [peerIdStr]),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Future<void> sendMessage(
    String? peerIdStr,
    _i14.Uint8List? message, {
    String? protocolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [peerIdStr, message],
              {#protocolId: protocolId},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i14.Uint8List?> sendRequest(
    String? peerId,
    String? protocolId,
    _i14.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i12.Future<_i14.Uint8List?>.value(),
          )
          as _i12.Future<_i14.Uint8List?>);

  @override
  _i12.Stream<_i14.Uint8List> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i12.Stream<_i14.Uint8List>.empty(),
          )
          as _i12.Stream<_i14.Uint8List>);

  @override
  void registerProtocolHandler(
    String? protocolId,
    void Function(_i13.NetworkPacket)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#registerProtocolHandler, [protocolId, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void removeMessageHandler(String? protocolId) => super.noSuchMethod(
    Invocation.method(#removeMessageHandler, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  void registerProtocol(String? protocolId) => super.noSuchMethod(
    Invocation.method(#registerProtocol, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> broadcastMessage(
    String? protocolId,
    _i14.Uint8List? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastMessage, [protocolId, message]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void emitEvent(String? topic, _i14.Uint8List? data) => super.noSuchMethod(
    Invocation.method(#emitEvent, [topic, data]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#onEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void offEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#offEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  Object? parseMultiaddr(String? multiaddr) =>
      (super.noSuchMethod(Invocation.method(#parseMultiaddr, [multiaddr]))
          as Object?);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
          )
          as List<String>);
}

/// A class which mocks [IPFSNode].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPFSNode extends _i1.Mock implements _i7.IPFSNode {
  MockIPFSNode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.NodeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i7.NodeState.stopped,
          )
          as _i7.NodeState);

  @override
  bool get isRunning =>
      (super.noSuchMethod(Invocation.getter(#isRunning), returnValue: false)
          as bool);

  @override
  String get peerId =>
      (super.noSuchMethod(
            Invocation.getter(#peerId),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#peerId),
            ),
          )
          as String);

  @override
  _i12.Stream<Map<String, dynamic>> get bandwidthMetrics =>
      (super.noSuchMethod(
            Invocation.getter(#bandwidthMetrics),
            returnValue: _i12.Stream<Map<String, dynamic>>.empty(),
          )
          as _i12.Stream<Map<String, dynamic>>);

  @override
  List<String> get addresses =>
      (super.noSuchMethod(
            Invocation.getter(#addresses),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i2.BlockStore get blockStore =>
      (super.noSuchMethod(
            Invocation.getter(#blockStore),
            returnValue: _FakeBlockStore_0(
              this,
              Invocation.getter(#blockStore),
            ),
          )
          as _i2.BlockStore);

  @override
  _i3.DHTClient get dhtClient =>
      (super.noSuchMethod(
            Invocation.getter(#dhtClient),
            returnValue: _FakeDHTClient_1(this, Invocation.getter(#dhtClient)),
          )
          as _i3.DHTClient);

  @override
  _i12.Future<List<String>> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<String> get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i12.Future<String>.value(
              _i11.dummyValue<String>(this, Invocation.getter(#publicKey)),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<List<String>> get pinnedCids =>
      (super.noSuchMethod(
            Invocation.getter(#pinnedCids),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Stream<_i15.PubSubMessage> get pubsubMessages =>
      (super.noSuchMethod(
            Invocation.getter(#pubsubMessages),
            returnValue: _i12.Stream<_i15.PubSubMessage>.empty(),
          )
          as _i12.Stream<_i15.PubSubMessage>);

  @override
  _i4.Datastore get datastore =>
      (super.noSuchMethod(
            Invocation.getter(#datastore),
            returnValue: _FakeDatastore_2(this, Invocation.getter(#datastore)),
          )
          as _i4.Datastore);

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  _i12.Stream<String> get onNewContent =>
      (super.noSuchMethod(
            Invocation.getter(#onNewContent),
            returnValue: _i12.Stream<String>.empty(),
          )
          as _i12.Stream<String>);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i12.Future<_i14.Uint8List?> cat(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#cat, [cid]),
            returnValue: _i12.Future<_i14.Uint8List?>.value(),
          )
          as _i12.Future<_i14.Uint8List?>);

  @override
  _i12.Future<void> connectToPeer(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#connectToPeer, [multiaddr]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> disconnectFromPeer(String? peerIdOrAddr) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromPeer, [peerIdOrAddr]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String> resolveIPNS(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#resolveIPNS, [name]),
            returnValue: _i12.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [name]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> subscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [topic]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> unsubscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [topic]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> publish(String? topic, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [topic, message]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> restart() =>
      (super.noSuchMethod(
            Invocation.method(#restart, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String> addFile(_i14.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#addFile, [data]),
            returnValue: _i12.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#addFile, [data]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<String> addFileStream(_i12.Stream<List<int>>? dataStream) =>
      (super.noSuchMethod(
            Invocation.method(#addFileStream, [dataStream]),
            returnValue: _i12.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#addFileStream, [dataStream]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<String> addDirectory(Map<String, dynamic>? directoryContent) =>
      (super.noSuchMethod(
            Invocation.method(#addDirectory, [directoryContent]),
            returnValue: _i12.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#addDirectory, [directoryContent]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  void setGatewayMode(_i7.GatewayMode? mode, {String? customUrl}) =>
      super.noSuchMethod(
        Invocation.method(#setGatewayMode, [mode], {#customUrl: customUrl}),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i14.Uint8List?> get(String? cid, {String? path = ''}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [cid], {#path: path}),
            returnValue: _i12.Future<_i14.Uint8List?>.value(),
          )
          as _i12.Future<_i14.Uint8List?>);

  @override
  _i12.Future<List<_i16.Link>> ls(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#ls, [cid]),
            returnValue: _i12.Future<List<_i16.Link>>.value(<_i16.Link>[]),
          )
          as _i12.Future<List<_i16.Link>>);

  @override
  _i12.Future<void> pin(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#pin, [cid]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> unpin(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#unpin, [cid]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> publishIPNS(String? cid, {required String? keyName}) =>
      (super.noSuchMethod(
            Invocation.method(#publishIPNS, [cid], {#keyName: keyName}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> importCAR(_i14.Uint8List? carFile) =>
      (super.noSuchMethod(
            Invocation.method(#importCAR, [carFile]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i14.Uint8List> exportCAR(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#exportCAR, [cid]),
            returnValue: _i12.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
          )
          as _i12.Future<_i14.Uint8List>);

  @override
  _i12.Future<List<String>> findProviders(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<void> requestBlock(String? cid, _i17.Peer? peer) =>
      (super.noSuchMethod(
            Invocation.method(#requestBlock, [cid, peer]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String> resolveDNSLink(String? domainName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDNSLink, [domainName]),
            returnValue: _i12.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#resolveDNSLink, [domainName]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<Map<String, dynamic>> getHealthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getHealthStatus, []),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);
}

/// A class which mocks [DHTHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockDHTHandler extends _i1.Mock implements _i18.DHTHandler {
  MockDHTHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DHTClient get dhtClient =>
      (super.noSuchMethod(
            Invocation.getter(#dhtClient),
            returnValue: _FakeDHTClient_1(this, Invocation.getter(#dhtClient)),
          )
          as _i3.DHTClient);

  @override
  _i5.RouterInterface get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRouterInterface_3(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i5.RouterInterface);

  @override
  _i4.Datastore get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeDatastore_2(this, Invocation.getter(#storage)),
          )
          as _i4.Datastore);

  @override
  set dhtClient(_i3.DHTClient? value) => super.noSuchMethod(
    Invocation.setter(#dhtClient, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i19.V_PeerInfo>> findProviders(_i20.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i12.Future<List<_i19.V_PeerInfo>>.value(
              <_i19.V_PeerInfo>[],
            ),
          )
          as _i12.Future<List<_i19.V_PeerInfo>>);

  @override
  _i12.Future<void> putValue(_i6.Key? key, _i6.Value? value) =>
      (super.noSuchMethod(
            Invocation.method(#putValue, [key, value]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i6.Value> getValue(_i6.Key? key) =>
      (super.noSuchMethod(
            Invocation.method(#getValue, [key]),
            returnValue: _i12.Future<_i6.Value>.value(
              _FakeValue_4(this, Invocation.method(#getValue, [key])),
            ),
          )
          as _i12.Future<_i6.Value>);

  @override
  _i12.Future<String> resolveIPNS(String? ipnsName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveIPNS, [ipnsName]),
            returnValue: _i12.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [ipnsName]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> publishIPNS(String? cid, {required String? keyName}) =>
      (super.noSuchMethod(
            Invocation.method(#publishIPNS, [cid], {#keyName: keyName}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  bool isValidCID(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#isValidCID, [cid]),
            returnValue: false,
          )
          as bool);

  @override
  bool isValidPeerID(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#isValidPeerID, [peerId]),
            returnValue: false,
          )
          as bool);

  @override
  String? extractCIDFromResponse(String? responseBody) =>
      (super.noSuchMethod(
            Invocation.method(#extractCIDFromResponse, [responseBody]),
          )
          as String?);

  @override
  _i12.Future<List<_i19.V_PeerInfo>> findPeer(_i9.PeerId? id) =>
      (super.noSuchMethod(
            Invocation.method(#findPeer, [id]),
            returnValue: _i12.Future<List<_i19.V_PeerInfo>>.value(
              <_i19.V_PeerInfo>[],
            ),
          )
          as _i12.Future<List<_i19.V_PeerInfo>>);

  @override
  _i12.Future<void> provide(_i20.CID? cid) =>
      (super.noSuchMethod(
            Invocation.method(#provide, [cid]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> handleRoutingTableUpdate(_i19.V_PeerInfo? peer) =>
      (super.noSuchMethod(
            Invocation.method(#handleRoutingTableUpdate, [peer]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> handleProvideRequest(_i20.CID? cid, _i9.PeerId? provider) =>
      (super.noSuchMethod(
            Invocation.method(#handleProvideRequest, [cid, provider]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> resolveDNSLink(String? domainName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDNSLink, [domainName]),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<Map<String, dynamic>> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);
}

/// A class which mocks [DHTClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDHTClient extends _i1.Mock implements _i3.DHTClient {
  MockDHTClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.IPFSNode get node =>
      (super.noSuchMethod(
            Invocation.getter(#node),
            returnValue: _FakeIPFSNode_5(this, Invocation.getter(#node)),
          )
          as _i7.IPFSNode);

  @override
  _i8.NetworkHandler get networkHandler =>
      (super.noSuchMethod(
            Invocation.getter(#networkHandler),
            returnValue: _FakeNetworkHandler_6(
              this,
              Invocation.getter(#networkHandler),
            ),
          )
          as _i8.NetworkHandler);

  @override
  _i9.PeerId get peerId =>
      (super.noSuchMethod(
            Invocation.getter(#peerId),
            returnValue: _FakePeerId_7(this, Invocation.getter(#peerId)),
          )
          as _i9.PeerId);

  @override
  _i9.PeerId get associatedPeerId =>
      (super.noSuchMethod(
            Invocation.getter(#associatedPeerId),
            returnValue: _FakePeerId_7(
              this,
              Invocation.getter(#associatedPeerId),
            ),
          )
          as _i9.PeerId);

  @override
  _i10.KademliaRoutingTable get kademliaRoutingTable =>
      (super.noSuchMethod(
            Invocation.getter(#kademliaRoutingTable),
            returnValue: _FakeKademliaRoutingTable_8(
              this,
              Invocation.getter(#kademliaRoutingTable),
            ),
          )
          as _i10.KademliaRoutingTable);

  @override
  _i5.RouterInterface get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeRouterInterface_3(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i5.RouterInterface);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  set peerId(_i9.PeerId? value) => super.noSuchMethod(
    Invocation.setter(#peerId, value),
    returnValueForMissingStub: null,
  );

  @override
  set associatedPeerId(_i9.PeerId? value) => super.noSuchMethod(
    Invocation.setter(#associatedPeerId, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i9.PeerId getRoutingKey(String? cidStr) =>
      (super.noSuchMethod(
            Invocation.method(#getRoutingKey, [cidStr]),
            returnValue: _FakePeerId_7(
              this,
              Invocation.method(#getRoutingKey, [cidStr]),
            ),
          )
          as _i9.PeerId);

  @override
  _i12.Future<List<_i9.PeerId>> findProviders(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i12.Future<List<_i9.PeerId>>.value(<_i9.PeerId>[]),
          )
          as _i12.Future<List<_i9.PeerId>>);

  @override
  _i12.Future<_i9.PeerId?> findPeer(_i9.PeerId? id) =>
      (super.noSuchMethod(
            Invocation.method(#findPeer, [id]),
            returnValue: _i12.Future<_i9.PeerId?>.value(),
          )
          as _i12.Future<_i9.PeerId?>);

  @override
  _i12.Future<void> addProvider(String? cid, String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#addProvider, [cid, providerId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> storeValue(_i14.Uint8List? key, _i14.Uint8List? value) =>
      (super.noSuchMethod(
            Invocation.method(#storeValue, [key, value]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> storeValueToPeer(
    _i9.PeerId? peer,
    _i14.Uint8List? key,
    _i14.Uint8List? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeValueToPeer, [peer, key, value]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<_i14.Uint8List?> getValue(_i14.Uint8List? key) =>
      (super.noSuchMethod(
            Invocation.method(#getValue, [key]),
            returnValue: _i12.Future<_i14.Uint8List?>.value(),
          )
          as _i12.Future<_i14.Uint8List?>);

  @override
  _i12.Future<bool> checkValueOnPeer(_i9.PeerId? peer, _i14.Uint8List? key) =>
      (super.noSuchMethod(
            Invocation.method(#checkValueOnPeer, [peer, key]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  bool listsEqual(List<int>? a, List<int>? b) =>
      (super.noSuchMethod(
            Invocation.method(#listsEqual, [a, b]),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Future<List<String>> getAllStoredKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getAllStoredKeys, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<void> updateKeyRepublishTime(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#updateKeyRepublishTime, [key]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [KademliaRoutingTable].
///
/// See the documentation for Mockito's code generation for more information.
class MockKademliaRoutingTable extends _i1.Mock
    implements _i10.KademliaRoutingTable {
  MockKademliaRoutingTable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DHTClient get dhtClient =>
      (super.noSuchMethod(
            Invocation.getter(#dhtClient),
            returnValue: _FakeDHTClient_1(this, Invocation.getter(#dhtClient)),
          )
          as _i3.DHTClient);

  @override
  int get peerCount =>
      (super.noSuchMethod(Invocation.getter(#peerCount), returnValue: 0)
          as int);

  @override
  List<_i21.RedBlackTree<_i9.PeerId, _i22.KademliaTreeNode>> get buckets =>
      (super.noSuchMethod(
            Invocation.getter(#buckets),
            returnValue:
                <_i21.RedBlackTree<_i9.PeerId, _i22.KademliaTreeNode>>[],
          )
          as List<_i21.RedBlackTree<_i9.PeerId, _i22.KademliaTreeNode>>);

  @override
  set dhtClient(_i3.DHTClient? value) => super.noSuchMethod(
    Invocation.setter(#dhtClient, value),
    returnValueForMissingStub: null,
  );

  @override
  void initialize(_i3.DHTClient? client) => super.noSuchMethod(
    Invocation.method(#initialize, [client]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> addPeer(
    _i9.PeerId? peerId,
    _i9.PeerId? associatedPeerId, {
    String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addPeer,
              [peerId, associatedPeerId],
              {#address: address},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void removePeer(_i9.PeerId? peerId) => super.noSuchMethod(
    Invocation.method(#removePeer, [peerId]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.PeerId? getAssociatedPeer(_i9.PeerId? peerId) =>
      (super.noSuchMethod(Invocation.method(#getAssociatedPeer, [peerId]))
          as _i9.PeerId?);

  @override
  bool containsPeer(_i9.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#containsPeer, [peerId]),
            returnValue: false,
          )
          as bool);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  int calculateDistance(_i9.PeerId? a, _i9.PeerId? b) =>
      (super.noSuchMethod(
            Invocation.method(#calculateDistance, [a, b]),
            returnValue: 0,
          )
          as int);

  @override
  List<_i9.PeerId> findClosestPeers(_i9.PeerId? target, int? k) =>
      (super.noSuchMethod(
            Invocation.method(#findClosestPeers, [target, k]),
            returnValue: <_i9.PeerId>[],
          )
          as List<_i9.PeerId>);

  @override
  _i12.Future<List<_i9.PeerId>> nodeLookup(_i9.PeerId? target) =>
      (super.noSuchMethod(
            Invocation.method(#nodeLookup, [target]),
            returnValue: _i12.Future<List<_i9.PeerId>>.value(<_i9.PeerId>[]),
          )
          as _i12.Future<List<_i9.PeerId>>);

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void addPeerToBucket(_i9.PeerId? peerId, _i9.PeerId? associatedPeerId) =>
      super.noSuchMethod(
        Invocation.method(#addPeerToBucket, [peerId, associatedPeerId]),
        returnValueForMissingStub: null,
      );

  @override
  void removePeerFromBucket(_i9.PeerId? peerId) => super.noSuchMethod(
    Invocation.method(#removePeerFromBucket, [peerId]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> updatePeer(_i19.V_PeerInfo? peer) =>
      (super.noSuchMethod(
            Invocation.method(#updatePeer, [peer]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addKeyProvider(
    _i9.PeerId? key,
    _i9.PeerId? provider,
    DateTime? timestamp,
  ) => super.noSuchMethod(
    Invocation.method(#addKeyProvider, [key, provider, timestamp]),
    returnValueForMissingStub: null,
  );

  @override
  void updateKeyProviderTimestamp(
    _i9.PeerId? key,
    _i9.PeerId? provider,
    DateTime? timestamp,
  ) => super.noSuchMethod(
    Invocation.method(#updateKeyProviderTimestamp, [key, provider, timestamp]),
    returnValueForMissingStub: null,
  );

  @override
  int distance(_i9.PeerId? a, _i9.PeerId? b) =>
      (super.noSuchMethod(Invocation.method(#distance, [a, b]), returnValue: 0)
          as int);

  @override
  _i12.Future<bool> pingPeer(_i9.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#pingPeer, [peerId]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}
