// Mocks generated by Mockito 5.4.6 from annotations
// in dart_ipfs/test/core/ipfs_node/pubsub_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;

import 'package:dart_ipfs/src/core/data_structures/node_stats.dart' as _i2;
import 'package:dart_ipfs/src/core/ipfs_node/ipfs_node_network_events.dart'
    as _i8;
import 'package:dart_ipfs/src/proto/generated/dht/ipfs_node_network_events.pb.dart'
    as _i9;
import 'package:dart_ipfs/src/protocols/pubsub/pubsub_client.dart' as _i10;
import 'package:dart_ipfs/src/protocols/pubsub/pubsub_message.dart' as _i11;
import 'package:dart_ipfs/src/transport/router_events.dart' as _i6;
import 'package:dart_ipfs/src/transport/router_interface.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNodeStats_0 extends _i1.SmartFake implements _i2.NodeStats {
  _FakeNodeStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RouterInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterInterface extends _i1.Mock implements _i3.RouterInterface {
  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  bool get hasStarted =>
      (super.noSuchMethod(
            Invocation.getter(#hasStarted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Set<String> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  _i5.Stream<_i6.ConnectionEvent> get connectionEvents =>
      (super.noSuchMethod(
            Invocation.getter(#connectionEvents),
            returnValue: _i5.Stream<_i6.ConnectionEvent>.empty(),
            returnValueForMissingStub: _i5.Stream<_i6.ConnectionEvent>.empty(),
          )
          as _i5.Stream<_i6.ConnectionEvent>);

  @override
  _i5.Stream<_i6.MessageEvent> get messageEvents =>
      (super.noSuchMethod(
            Invocation.getter(#messageEvents),
            returnValue: _i5.Stream<_i6.MessageEvent>.empty(),
            returnValueForMissingStub: _i5.Stream<_i6.MessageEvent>.empty(),
          )
          as _i5.Stream<_i6.MessageEvent>);

  @override
  List<String> get listeningAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#listeningAddresses),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> connect(String? multiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [multiaddress]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> disconnect(String? peerIdOrMultiaddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [peerIdOrMultiaddress]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<String> listConnectedPeers() =>
      (super.noSuchMethod(
            Invocation.method(#listConnectedPeers, []),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool isConnectedPeer(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#isConnectedPeer, [peerIdStr]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> sendMessage(
    String? peerIdStr,
    _i7.Uint8List? message, {
    String? protocolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [peerIdStr, message],
              {#protocolId: protocolId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i7.Uint8List?> sendRequest(
    String? peerId,
    String? protocolId,
    _i7.Uint8List? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [peerId, protocolId, request]),
            returnValue: _i5.Future<_i7.Uint8List?>.value(),
            returnValueForMissingStub: _i5.Future<_i7.Uint8List?>.value(),
          )
          as _i5.Future<_i7.Uint8List?>);

  @override
  _i5.Stream<_i7.Uint8List> receiveMessages(String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#receiveMessages, [peerId]),
            returnValue: _i5.Stream<_i7.Uint8List>.empty(),
            returnValueForMissingStub: _i5.Stream<_i7.Uint8List>.empty(),
          )
          as _i5.Stream<_i7.Uint8List>);

  @override
  void registerProtocolHandler(
    String? protocolId,
    void Function(_i6.NetworkPacket)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#registerProtocolHandler, [protocolId, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void removeMessageHandler(String? protocolId) => super.noSuchMethod(
    Invocation.method(#removeMessageHandler, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  void registerProtocol(String? protocolId) => super.noSuchMethod(
    Invocation.method(#registerProtocol, [protocolId]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> broadcastMessage(
    String? protocolId,
    _i7.Uint8List? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastMessage, [protocolId, message]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emitEvent(String? topic, _i7.Uint8List? data) => super.noSuchMethod(
    Invocation.method(#emitEvent, [topic, data]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#onEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void offEvent(String? topic, void Function(dynamic)? handler) =>
      super.noSuchMethod(
        Invocation.method(#offEvent, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  Object? parseMultiaddr(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#parseMultiaddr, [multiaddr]),
            returnValueForMissingStub: null,
          )
          as Object?);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);
}

/// A class which mocks [IpfsNodeNetworkEvents].
///
/// See the documentation for Mockito's code generation for more information.
class MockIpfsNodeNetworkEvents extends _i1.Mock
    implements _i8.IpfsNodeNetworkEvents {
  @override
  _i5.Stream<_i9.NetworkEvent> get networkEvents =>
      (super.noSuchMethod(
            Invocation.getter(#networkEvents),
            returnValue: _i5.Stream<_i9.NetworkEvent>.empty(),
            returnValueForMissingStub: _i5.Stream<_i9.NetworkEvent>.empty(),
          )
          as _i5.Stream<_i9.NetworkEvent>);

  @override
  void start() => super.noSuchMethod(
    Invocation.method(#start, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PubSubClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPubSubClient extends _i1.Mock implements _i10.PubSubClient {
  @override
  bool get isStarted =>
      (super.noSuchMethod(
            Invocation.getter(#isStarted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Stream<_i11.PubSubMessage> get messagesStream =>
      (super.noSuchMethod(
            Invocation.getter(#messagesStream),
            returnValue: _i5.Stream<_i11.PubSubMessage>.empty(),
            returnValueForMissingStub: _i5.Stream<_i11.PubSubMessage>.empty(),
          )
          as _i5.Stream<_i11.PubSubMessage>);

  @override
  _i5.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> subscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [topic]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [topic]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> publish(String? topic, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [topic, message]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onMessage(String? topic, void Function(String)? handler) =>
      super.noSuchMethod(
        Invocation.method(#onMessage, [topic, handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Uint8List encodeSubscribeRequest(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#encodeSubscribeRequest, [topic]),
            returnValue: _i7.Uint8List(0),
            returnValueForMissingStub: _i7.Uint8List(0),
          )
          as _i7.Uint8List);

  @override
  _i7.Uint8List encodeUnsubscribeRequest(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#encodeUnsubscribeRequest, [topic]),
            returnValue: _i7.Uint8List(0),
            returnValueForMissingStub: _i7.Uint8List(0),
          )
          as _i7.Uint8List);

  @override
  _i7.Uint8List encodePublishRequest(String? topic, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#encodePublishRequest, [topic, message]),
            returnValue: _i7.Uint8List(0),
            returnValueForMissingStub: _i7.Uint8List(0),
          )
          as _i7.Uint8List);

  @override
  String decodeMessage(_i7.Uint8List? messageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#decodeMessage, [messageBytes]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#decodeMessage, [messageBytes]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#decodeMessage, [messageBytes]),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.NodeStats> getNodeStats() =>
      (super.noSuchMethod(
            Invocation.method(#getNodeStats, []),
            returnValue: _i5.Future<_i2.NodeStats>.value(
              _FakeNodeStats_0(this, Invocation.method(#getNodeStats, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.NodeStats>.value(
              _FakeNodeStats_0(this, Invocation.method(#getNodeStats, [])),
            ),
          )
          as _i5.Future<_i2.NodeStats>);

  @override
  void graftPeer(String? peerId) => super.noSuchMethod(
    Invocation.method(#graftPeer, [peerId]),
    returnValueForMissingStub: null,
  );

  @override
  void prunePeer(String? peerId) => super.noSuchMethod(
    Invocation.method(#prunePeer, [peerId]),
    returnValueForMissingStub: null,
  );
}
